'use client';

import Link from 'next/link';
import { useLocale } from 'next-intl';
import { useEffect, useState } from 'react';
import { getApiV1AdminAlbums, getApiV1AdminAlbumsAlbumId } from '@/lib/api/admin-browser';
import type { AdminAlbumDetail, AdminAlbumSummary } from '@/lib/api/generated/index.schemas';
import { AdminCard, AdminEmpty, AdminError, AdminPage, AdminPagination, AdminStatus, formatAdminDate, formatAdminNumber, type AdminLocale } from './common';

export function AdminAlbums() {
  const locale = (useLocale() === 'en' ? 'en' : 'id') as AdminLocale; const id = locale === 'id';
  const [rows, setRows] = useState<AdminAlbumSummary[]>([]); const [cursor, setCursor] = useState<string | null>(null); const [more, setMore] = useState(false); const [busy, setBusy] = useState(true); const [error, setError] = useState<number>();
  async function load(next?: string) { setBusy(true); setError(undefined); try { const r = await getApiV1AdminAlbums({ limit: 25, ...(next ? { cursor: next } : {}) }); if (r.status === 200) { setRows(r.data.data); setCursor(r.data.meta.next_cursor ?? null); setMore(r.data.meta.has_more); } else setError(r.status); } catch { setError(0); } finally { setBusy(false); } }
  // eslint-disable-next-line react-hooks/set-state-in-effect -- start the initial server read after mount
  useEffect(() => { void load(); }, []);
  return <AdminPage title={id ? 'Album' : 'Albums'} description={id ? 'Metadata operasional saja. Membuka detail tidak memberikan akses ke media privat atau kemampuan Pemilik.' : 'Operational metadata only. Opening a detail does not grant private-media access or Owner capabilities.'}>
    {error !== undefined ? <AdminError locale={locale} status={error} retry={() => void load()} /> : <AdminCard title={id ? 'Semua album' : 'All albums'}>
      {busy && <p role="status">{id ? 'Memuat album…' : 'Loading albums…'}</p>}
      {!busy && rows.length === 0 ? <AdminEmpty>{id ? 'Belum ada album untuk ditampilkan.' : 'No albums to display.'}</AdminEmpty> : <>
        <div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[56rem] text-left text-sm"><thead><tr className="border-b border-[var(--color-border)] text-xs uppercase text-[var(--color-muted-foreground)]"><th className="p-3">{id ? 'Acara / Pemilik' : 'Event / Owner'}</th><th className="p-3">{id ? 'Kesiapan' : 'Readiness'}</th><th className="p-3">{id ? 'Jadwal potret' : 'Capture window'}</th><th className="p-3">{id ? 'Kapasitas' : 'Quota'}</th><th className="p-3">{id ? 'Hold' : 'Hold'}</th><th className="p-3" /></tr></thead><tbody>{rows.map(a => <tr key={a.album_id} className="border-b border-[var(--color-border)]"><td className="max-w-80 break-words p-3"><b>{a.event_name || (id ? 'Acara tanpa nama' : 'Untitled event')}</b><span className="block break-all text-xs text-[var(--color-muted-foreground)]">{a.owner_email} · {a.album_id}</span></td><td className="p-3"><AdminStatus value={a.readiness} /></td><td className="whitespace-nowrap p-3">{formatAdminDate(a.capture_start, locale)}<br />{formatAdminDate(a.capture_end, locale)}</td><td className="p-3 tabular-nums">{formatAdminNumber(a.committed_count, locale)} / {a.quota_total == null ? '—' : formatAdminNumber(a.quota_total, locale)}<span className="block text-xs text-[var(--color-muted-foreground)]">{formatAdminNumber(a.reserved_count, locale)} {id ? 'dicadangkan' : 'reserved'}</span></td><td className="p-3"><AdminStatus value={a.hold_active ? 'ACTIVE HOLD' : 'NONE'} /></td><td className="p-3"><Link className="font-semibold underline underline-offset-4" href={`/admin/albums/${encodeURIComponent(a.album_id)}`}>{id ? 'Detail' : 'Details'}</Link></td></tr>)}</tbody></table></div>
        <ul className="space-y-3 md:hidden">{rows.map(a => <li key={a.album_id} className="rounded-[var(--radius-md)] border border-[var(--color-border)] p-3"><div className="flex flex-wrap justify-between gap-2"><strong className="min-w-0 break-words">{a.event_name || (id ? 'Acara tanpa nama' : 'Untitled event')}</strong><AdminStatus value={a.readiness} /></div><p className="mt-1 break-all text-xs text-[var(--color-muted-foreground)]">{a.owner_email} · {a.album_id}</p><dl className="mt-3 grid grid-cols-2 gap-2 text-xs"><div><dt>{id ? 'Foto' : 'Photos'}</dt><dd>{formatAdminNumber(a.committed_count, locale)} / {a.quota_total ?? '—'}</dd></div><div><dt>{id ? 'Hold' : 'Hold'}</dt><dd>{a.hold_active ? 'ACTIVE' : 'NONE'}</dd></div></dl><Link className="mt-2 inline-flex min-h-11 items-center font-semibold underline" href={`/admin/albums/${encodeURIComponent(a.album_id)}`}>{id ? 'Buka diagnostik' : 'Open diagnostics'}</Link></li>)}</ul>
      </>}
      <AdminPagination hasMore={more} cursor={cursor} busy={busy} locale={locale} onNext={() => cursor && void load(cursor)} />
    </AdminCard>}
  </AdminPage>;
}

export function AdminAlbumDetailPage({ albumId }: { albumId: string }) {
  const locale = (useLocale() === 'en' ? 'en' : 'id') as AdminLocale; const id = locale === 'id';
  const [data, setData] = useState<AdminAlbumDetail | null>(null); const [busy, setBusy] = useState(true); const [error, setError] = useState<number>();
  async function load() { setBusy(true); setError(undefined); try { const r = await getApiV1AdminAlbumsAlbumId(albumId); if (r.status === 200) setData(r.data.data); else setError(r.status); } catch { setError(0); } finally { setBusy(false); } }
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps -- reload when the route album changes
  useEffect(() => { void load(); }, [albumId]); const a = data?.summary;
  return <AdminPage title={id ? 'Diagnostik album' : 'Album diagnostics'} description={id ? 'Semua informasi di sini bersifat operasional dan hanya-baca. Tidak ada kontrol Pemilik atau media privat.' : 'All information here is operational and read-only. No Owner controls or private media are included.'}>
    {error !== undefined ? <AdminError locale={locale} status={error} retry={() => void load()} /> : busy ? <p role="status">{id ? 'Memuat diagnostik…' : 'Loading diagnostics…'}</p> : !data || !a ? <AdminEmpty>{id ? 'Album tidak ditemukan.' : 'Album not found.'}</AdminEmpty> : <>
      <AdminCard title={a.event_name || (id ? 'Acara tanpa nama' : 'Untitled event')}><dl className="grid gap-4 text-sm sm:grid-cols-2 xl:grid-cols-3"><div><dt className="text-xs text-[var(--color-muted-foreground)]">ID</dt><dd className="break-all font-mono">{a.album_id}</dd></div><div><dt className="text-xs text-[var(--color-muted-foreground)]">{id ? 'Pemilik (referensi)' : 'Owner reference'}</dt><dd className="break-all">{data.summary.owner_email}<br /><span className="font-mono text-xs">{data.summary.owner_user_id}</span></dd></div><div><dt>{id ? 'Kesiapan' : 'Readiness'}</dt><dd><AdminStatus value={a.readiness} /></dd></div><div><dt>{id ? 'Jadwal potret' : 'Capture schedule'}</dt><dd>{formatAdminDate(a.capture_start, locale)} – {formatAdminDate(a.capture_end, locale)}<br />{data.timezone}</dd></div><div><dt>{id ? 'Kuota foto' : 'Photo quota'}</dt><dd>{formatAdminNumber(a.committed_count, locale)} {id ? 'tersimpan' : 'committed'} · {formatAdminNumber(a.reserved_count, locale)} {id ? 'dicadangkan' : 'reserved'} / {a.quota_total ?? '—'}</dd></div><div><dt>{id ? 'Status Hold' : 'Hold status'}</dt><dd><AdminStatus value={a.hold_active ? 'ACTIVE HOLD' : 'NONE'} /></dd></div></dl></AdminCard>
      <div className="grid gap-4 lg:grid-cols-2"><AdminCard title={id ? 'Aksi operasional kontekstual' : 'Contextual operational actions'}><p className="text-sm leading-6 text-[var(--color-muted-foreground)]">{id ? 'Akses Sensitif dan Operational Hold adalah wewenang terpisah. Masing-masing memerlukan MFA step-up dan alasan.' : 'Sensitive Access and Operational Hold are separate authorities. Each requires MFA step-up and a reason.'}</p><div className="mt-4 flex flex-wrap gap-2"><Link className="inline-flex min-h-11 items-center rounded-[var(--radius-md)] border border-[var(--color-border)] px-4 text-sm font-semibold hover:bg-[var(--color-muted)]" href={`/admin/albums/${encodeURIComponent(albumId)}/sensitive-access`}>{id ? 'Akses media sensitif' : 'Sensitive media access'}</Link><Link className="inline-flex min-h-11 items-center rounded-[var(--radius-md)] border border-[var(--color-border)] px-4 text-sm font-semibold hover:bg-[var(--color-muted)]" href={`/admin/albums/${encodeURIComponent(albumId)}/hold`}>{id ? 'Kelola Operational Hold' : 'Manage Operational Hold'}</Link></div></AdminCard><AdminCard title={id ? 'Siklus hidup' : 'Lifecycle'}>{data.lifecycle ? <dl className="space-y-3 text-sm"><div><dt>{id ? 'Akses normal berakhir' : 'Normal access ends'}</dt><dd>{formatAdminDate(data.lifecycle.normal_access_end_at, locale)}</dd></div><div><dt>{id ? 'Pemulihan berakhir' : 'Recovery ends'}</dt><dd>{formatAdminDate(data.lifecycle.recovery_end_at, locale)}</dd></div><div><dt>{id ? 'Pembersihan cadangan' : 'Backup cleanup'}</dt><dd>{formatAdminDate(data.lifecycle.backup_cleanup_deadline_at, locale)}</dd></div></dl> : <p>{id ? 'Tidak tersedia' : 'Not available'}</p>}</AdminCard></div>
      <AdminCard title={id ? 'Transaksi terkait' : 'Related transactions'}>{data.payment_transactions.length ? <ul className="space-y-2">{data.payment_transactions.map(p => <li key={p.transaction_id} className="flex flex-wrap justify-between gap-2 border-b border-[var(--color-border)] py-2 text-sm"><span className="break-all font-mono">{p.transaction_id}</span><Link className="font-semibold underline" href={`/admin/payments/${encodeURIComponent(p.transaction_id)}`}>{id ? 'Diagnosis' : 'Diagnosis'}</Link></li>)}</ul> : <p className="text-sm text-[var(--color-muted-foreground)]">{id ? 'Tidak ada transaksi terkait.' : 'No related transactions.'}</p>}</AdminCard>
      <AdminCard title={id ? 'Isu terkait' : 'Related issues'}>{data.related_issues.length ? <ul className="space-y-2">{data.related_issues.map(i => <li key={i.issue_id} className="border-b border-[var(--color-border)] py-2 text-sm"><Link className="font-semibold underline" href={`/admin/issues/${encodeURIComponent(i.issue_id)}`}>{i.summary}</Link><p className="font-mono text-xs">{i.issue_id}</p></li>)}</ul> : <p className="text-sm text-[var(--color-muted-foreground)]">{id ? 'Tidak ada isu terkait.' : 'No related issues.'}</p>}</AdminCard>
    </>}
  </AdminPage>;
}
