'use client';

import Link from 'next/link';
import { useLocale } from 'next-intl';
import { useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import { ConfirmDialog } from '@/components/ui/confirm-dialog';
import {
  getApiV1AdminPayments, getApiV1AdminPaymentsTransactionId, postApiV1AdminPaymentsTransactionIdReconcile,
  getApiV1AdminPackages, postApiV1AdminPackagesPackageIdVersions, getApiV1AdminOperationalConfigs, patchApiV1AdminOperationalConfigsKey,
  getApiV1AdminIssues, getApiV1AdminIssuesIssueId, postApiV1AdminIssuesIssueIdAcknowledge, postApiV1AdminIssuesIssueIdResolve,
  getApiV1AdminAuditLogs, getApiV1AdminAuditLogsAuditId, getApiV1AdminAdmins, getApiV1AdminEventCategories, postApiV1AdminEventCategories, patchApiV1AdminEventCategoriesCategoryId,
  patchApiV1AdminPackageVersionsVersionIdSaleStatus,
} from '@/lib/api/admin-browser';
import type { AdminPackage, AdminPackageVersion, AdminPaymentDiagnosis, AdminAuditLogSummary, AdminRosterEntry, EventCategory, OperationalConfig, OperationalIssue, PaymentTransaction, PackageVersionCreateRequest } from '@/lib/api/generated/index.schemas';
import { createUuidV7 } from '@/features/guest/lib/idempotency';
import { AdminCard, AdminEmpty, AdminError, AdminFeedback, AdminField, AdminOfflineNote, AdminPage, AdminPagination, AdminStatus, adminCsrfHeaders, adminInputClass, formatAdminDate, formatAdminNumber, type AdminLocale, useAdminOnline } from './common';

function useCopy() { const locale = (useLocale() === 'en' ? 'en' : 'id') as AdminLocale; return { locale, id: locale === 'id' }; }

export function AdminPayments() {
  const { locale, id } = useCopy(); const [rows, setRows] = useState<PaymentTransaction[]>([]); const [cursor, setCursor] = useState<string | null>(null); const [more, setMore] = useState(false); const [busy, setBusy] = useState(true); const [error, setError] = useState<number>();
  async function load(next?: string) { setBusy(true); setError(undefined); try { const r = await getApiV1AdminPayments({ limit: 25, ...(next ? { cursor: next } : {}) }); if (r.status === 200) { setRows(r.data.data); setCursor(r.data.meta.next_cursor ?? null); setMore(r.data.meta.has_more); } else setError(r.status); } catch { setError(0); } finally { setBusy(false); } }
  // eslint-disable-next-line react-hooks/set-state-in-effect -- start the initial server read after mount
  useEffect(() => { void load(); }, []);
  return <AdminPage title={id ? 'Pembayaran' : 'Payments'} description={id ? 'Diagnosis transaksi dan pemeriksaan ulang provider. Tidak ada tindakan untuk menandai berhasil, memberi entitlement, mengubah kuota, atau refund.' : 'Transaction diagnosis and provider re-checks. There are no actions to mark success, grant entitlements, change quota, or refund.'}>{error !== undefined ? <AdminError locale={locale} status={error} retry={() => void load()} /> : <AdminCard title={id ? 'Transaksi' : 'Transactions'}>
    {busy && <p role="status">{id ? 'Memuat transaksi…' : 'Loading transactions…'}</p>}{!busy && rows.length === 0 ? <AdminEmpty>{id ? 'Tidak ada transaksi.' : 'No transactions.'}</AdminEmpty> : <div className="space-y-2">{rows.map(p => <Link key={p.transaction_id} href={`/admin/payments/${encodeURIComponent(p.transaction_id)}`} className="grid gap-2 rounded-[var(--radius-md)] border border-[var(--color-border)] p-3 text-sm hover:bg-[var(--color-muted)] sm:grid-cols-[minmax(0,1fr)_auto_auto] sm:items-center"><span className="min-w-0"><b className="block">{p.package_name_snapshot} · {p.type}</b><span className="break-all font-mono text-xs text-[var(--color-muted-foreground)]">{p.transaction_id}</span></span><AdminStatus value={p.status} /><span className="whitespace-nowrap tabular-nums">{new Intl.NumberFormat(id ? 'id-ID' : 'en-US',{style:'currency',currency:p.currency}).format(p.amount)}</span></Link>)}</div>}
    <AdminPagination hasMore={more} cursor={cursor} busy={busy} locale={locale} onNext={() => cursor && void load(cursor)} />
  </AdminCard>}</AdminPage>;
}

export function AdminPaymentDetail({ transactionId }: { transactionId: string }) {
  const { locale, id } = useCopy(); const online = useAdminOnline(); const [data, setData] = useState<AdminPaymentDiagnosis | null>(null); const [busy, setBusy] = useState(true); const [error, setError] = useState<number>(); const [working, setWorking] = useState(false); const [confirm, setConfirm] = useState(false); const [message, setMessage] = useState('');
  async function load() { setBusy(true); setError(undefined); try { const r = await getApiV1AdminPaymentsTransactionId(transactionId); if (r.status === 200) setData(r.data.data); else setError(r.status); } catch { setError(0); } finally { setBusy(false); } }
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps -- reload when the route transaction changes
  useEffect(() => { void load(); }, [transactionId]);
  async function reconcile() { setWorking(true); setError(undefined); setMessage(''); try { const r = await postApiV1AdminPaymentsTransactionIdReconcile(transactionId, { headers: await adminCsrfHeaders() }); if (r.status === 200) { setData(r.data.data); setMessage(id ? 'Respons provider dan transaksi terbaru telah dimuat dari server.' : 'Latest provider response and transaction state loaded from the server.'); } else setError(r.status); } catch { setError(0); } finally { setWorking(false); setConfirm(false); } }
  const p = data?.transaction;
  return <AdminPage title={id ? 'Diagnosis pembayaran' : 'Payment diagnosis'} description={id ? 'Rekonsiliasi hanya meminta pemeriksaan ulang ke provider. Tidak mengubah hasil secara manual.' : 'Reconciliation only requests a provider re-check. It does not manually alter the outcome.'}>{error !== undefined ? <AdminError locale={locale} status={error} retry={() => void load()} /> : busy ? <p role="status">{id ? 'Memuat diagnosis…' : 'Loading diagnosis…'}</p> : !data || !p ? <AdminEmpty>{id ? 'Transaksi tidak ditemukan.' : 'Transaction not found.'}</AdminEmpty> : <>
    <AdminCard title={p.package_name_snapshot}><dl className="grid gap-4 text-sm sm:grid-cols-2"><div><dt>{id ? 'ID transaksi' : 'Transaction ID'}</dt><dd className="break-all font-mono">{p.transaction_id}</dd></div><div><dt>{id ? 'Album' : 'Album'}</dt><dd className="break-all font-mono">{p.album_id}</dd></div><div><dt>{id ? 'Status server' : 'Server status'}</dt><dd><AdminStatus value={p.status} /></dd></div><div><dt>{id ? 'Jenis' : 'Type'}</dt><dd>{p.type}</dd></div><div><dt>{id ? 'Nilai snapshot' : 'Snapshot amount'}</dt><dd>{new Intl.NumberFormat(id ? 'id-ID' : 'en-US',{style:'currency',currency:p.currency}).format(p.amount)}</dd></div><div><dt>{id ? 'Kuota target snapshot' : 'Snapshot target quota'}</dt><dd>{formatAdminNumber(p.target_quota_total_snapshot, locale)}</dd></div><div><dt>{id ? 'Batas pembayaran' : 'Payment cutoff'}</dt><dd>{formatAdminDate(p.payment_cutoff_at, locale)}</dd></div><div><dt>{id ? 'Entitlement saat ini' : 'Current entitlement'}</dt><dd>{data.entitlement ? JSON.stringify(data.entitlement) : (id ? 'Tidak ada proyeksi' : 'No projection')}</dd></div></dl></AdminCard>
    <AdminCard title={id ? 'Ringkasan tanda terima provider' : 'Provider receipt diagnostics'}>{data.receipt_diagnostics.length ? <ul className="space-y-3">{data.receipt_diagnostics.map(x => <li key={x.receipt_id} className="rounded-[var(--radius-md)] border border-[var(--color-border)] p-3 text-sm"><p className="font-semibold">{x.source} · {x.provider_state ?? '—'}</p><p>{id ? 'Tanda tangan terverifikasi' : 'Signature verified'}: {x.signature_verified ? 'Yes' : 'No'} · {x.process_result ?? '—'} · {x.error_code ?? '—'}</p><p className="text-xs text-[var(--color-muted-foreground)]">{formatAdminDate(x.received_at, locale)} · {formatAdminDate(x.processed_at, locale)}</p></li>)}</ul> : <AdminEmpty>{id ? 'Belum ada ringkasan provider.' : 'No provider receipt summaries.'}</AdminEmpty>}
      <p className="mt-4 text-sm">{id ? 'Tindakan yang tersedia: pemeriksaan ulang provider saja.' : 'Available action: provider re-check only.'}</p><Button className="mt-3" disabled={!online || working || !data.can_reconcile} loading={working} onClick={() => setConfirm(true)}>{id ? 'Periksa ulang ke provider' : 'Re-check with provider'}</Button>
      {message && <div className="mt-3"><AdminFeedback kind="status">{message}</AdminFeedback></div>}{error !== undefined && <div className="mt-3"><AdminFeedback>{error === 503 ? (id ? 'Provider atau layanan pendukung tidak tersedia. Tidak ada perubahan manual yang dilakukan.' : 'Provider or supporting service is unavailable. No manual state change was made.') : `HTTP ${error || 'network'}`}</AdminFeedback></div>}
    </AdminCard></>}
    <ConfirmDialog open={confirm} title={id ? 'Periksa status provider?' : 'Re-check provider status?'} description={id ? 'Permintaan ini memeriksa status provider dan mengembalikan hasil server. Tidak ada pembayaran yang akan ditandai berhasil secara manual.' : 'This requests the provider state and returns the server result. No payment will be manually marked successful.'} confirmLabel={id ? 'Lanjutkan' : 'Continue'} cancelLabel={id ? 'Batal' : 'Cancel'} onCancel={() => setConfirm(false)} onConfirm={() => void reconcile()} disabled={working || !online} />
  </AdminPage>;
}

export function AdminPackages() {
  const { locale,id }=useCopy(); const online=useAdminOnline(); const [rows,setRows]=useState<AdminPackage[]>([]); const [cursor,setCursor]=useState<string|null>(null); const [more,setMore]=useState(false); const [error,setError]=useState<number>(); const [busy,setBusy]=useState(true); const [pendingSale,setPendingSale]=useState<{version:AdminPackageVersion; enabled:boolean}|null>(null); const [savingSale,setSavingSale]=useState(false);
  async function load(next?:string){setBusy(true);setError(undefined);try{const r=await getApiV1AdminPackages({limit:25,...(next?{cursor:next}:{})});if(r.status===200){setRows(r.data.data);setCursor(r.data.meta.next_cursor??null);setMore(r.data.meta.has_more)}else setError(r.status)}catch{setError(0)}finally{setBusy(false)}}
  // eslint-disable-next-line react-hooks/set-state-in-effect -- start the initial server read after mount
  useEffect(()=>{void load()},[]);
  async function toggleSale(){if(!pendingSale||!online)return;setSavingSale(true);setError(undefined);try{const r=await patchApiV1AdminPackageVersionsVersionIdSaleStatus(pendingSale.version.package_version_id,{sale_enabled:pendingSale.enabled},{headers:await adminCsrfHeaders()});if(r.status===200){setPendingSale(null);await load()}else setError(r.status)}catch{setError(0)}finally{setSavingSale(false)}}
  return <AdminPage title={id?'Katalog paket':'Package catalog'} description={id?'Versi historis tidak dapat diedit. Perubahan harga/kuota dilakukan dengan menambah versi paket baru.':'Historical versions are immutable. Price/quota changes create a new package version.'}>{error!==undefined?<AdminError locale={locale} status={error} retry={()=>void load()}/>:<>
    {busy&&<p role="status">{id?'Memuat katalog…':'Loading catalog…'}</p>}{!busy&&rows.length===0?<AdminEmpty>{id?'Belum ada paket.':'No packages.'}</AdminEmpty>:rows.map(pkg=><AdminCard key={pkg.package_id} title={`${pkg.name} · ${pkg.code}`}><p className="break-all font-mono text-xs">{pkg.package_id}</p><div className="mt-3 space-y-2">{pkg.versions.map(v=><div key={v.package_version_id} className="grid gap-2 rounded border border-[var(--color-border)] p-3 text-sm sm:grid-cols-[minmax(0,1fr)_auto_auto_auto] sm:items-center"><span className="break-all font-mono text-xs">{v.package_version_id}</span><span>{new Intl.NumberFormat(id?'id-ID':'en-US',{style:'currency',currency:v.currency}).format(v.price_amount)}</span><span>{formatAdminNumber(v.quota_total,locale)} {id?'foto':'photos'}</span><div className="flex items-center gap-2"><AdminStatus value={v.sale_enabled?'SALE ENABLED':'RETIRED'}/><Button variant="secondary" disabled={!online} onClick={()=>setPendingSale({version:v,enabled:!v.sale_enabled})}>{v.sale_enabled?(id?'Pensiunkan':'Retire'):(id?'Aktifkan':'Enable')}</Button></div></div>)}</div><Link className="mt-4 inline-flex min-h-11 items-center font-semibold underline" href={`/admin/catalog/packages/${encodeURIComponent(pkg.package_id)}/versions/new`}>{id?'Buat versi baru':'Create new version'}</Link></AdminCard>)}
    <Link className="inline-flex min-h-11 items-center font-semibold underline" href="/admin/catalog/categories">{id?'Kelola kategori acara':'Manage event categories'}</Link>
    <AdminPagination hasMore={more} cursor={cursor} busy={busy} locale={locale} onNext={()=>cursor&&void load(cursor)}/></>}<ConfirmDialog open={!!pendingSale} title={pendingSale?.enabled?(id?'Aktifkan penjualan?':'Enable sales?'):(id?'Pensiunkan versi?':'Retire this version?')} description={id?'Tindakan hanya mengubah ketersediaan checkout mendatang. Harga, kuota, dan snapshot transaksi historis tidak berubah.':'This only changes availability for future checkout. Price, quota, and historical transaction snapshots remain unchanged.'} confirmLabel={id?'Konfirmasi':'Confirm'} cancelLabel={id?'Batal':'Cancel'} destructive={!pendingSale?.enabled} onCancel={()=>setPendingSale(null)} onConfirm={()=>void toggleSale()} disabled={savingSale||!online}/></AdminPage>;
}

export function AdminCategories(){
 const {locale,id}=useCopy();const online=useAdminOnline();const [rows,setRows]=useState<EventCategory[]>([]);const [busy,setBusy]=useState(true);const [working,setWorking]=useState(false);const [error,setError]=useState<number>();const [code,setCode]=useState('');const [labelId,setLabelId]=useState('');const [labelEn,setLabelEn]=useState('');const [order,setOrder]=useState('0');const [notice,setNotice]=useState('');
 async function load(){setBusy(true);setError(undefined);try{const r=await getApiV1AdminEventCategories({limit:100});if(r.status===200)setRows(r.data.data);else setError(r.status)}catch{setError(0)}finally{setBusy(false)}}
 // eslint-disable-next-line react-hooks/set-state-in-effect -- start the initial server read after mount
 useEffect(()=>{void load()},[]);
 async function create(e:React.FormEvent){e.preventDefault();if(!online||working)return;setWorking(true);setError(undefined);try{const r=await postApiV1AdminEventCategories({code:code.trim(),label_id:labelId.trim(),label_en:labelEn.trim(),display_order:Number(order),active:true},{headers:await adminCsrfHeaders()});if(r.status===201){setCode('');setLabelId('');setLabelEn('');setOrder('0');await load()}else setError(r.status)}catch{setError(0)}finally{setWorking(false)}}
 async function toggle(c:EventCategory){setWorking(true);setError(undefined);try{const r=await patchApiV1AdminEventCategoriesCategoryId(c.category_id,{active:!c.active},{headers:await adminCsrfHeaders()});if(r.status===200){setNotice(id?'Status kategori diperbarui; identitas tetap disimpan.':'Category status updated; its identity is retained.');await load()}else setError(r.status)}catch{setError(0)}finally{setWorking(false)}}
 return <AdminPage title={id?'Kategori acara':'Event categories'} description={id?'Kategori dapat dinonaktifkan tanpa menghapus identitas historis.':'Categories can be deactivated without deleting historical identity.'}><AdminOfflineNote online={online} locale={locale}/>{error!==undefined&&<AdminError locale={locale} status={error} retry={()=>void load()}/ >}{notice&&<AdminFeedback kind="status">{notice}</AdminFeedback>}<AdminCard title={id?'Tambah kategori':'Add category'}><form onSubmit={e=>void create(e)} className="grid gap-3 sm:grid-cols-2"><AdminField label="Code"><input className={adminInputClass} maxLength={50} required value={code} onChange={e=>setCode(e.target.value)}/></AdminField><AdminField label={id?'Label Indonesia':'Indonesian label'}><input className={adminInputClass} maxLength={100} required value={labelId} onChange={e=>setLabelId(e.target.value)}/></AdminField><AdminField label={id?'Label Inggris':'English label'}><input className={adminInputClass} maxLength={100} required value={labelEn} onChange={e=>setLabelEn(e.target.value)}/></AdminField><AdminField label={id?'Urutan':'Display order'}><input type="number" className={adminInputClass} required value={order} onChange={e=>setOrder(e.target.value)}/></AdminField><Button className="sm:col-span-2 sm:justify-self-start" disabled={!online||working} loading={working}>{id?'Buat kategori':'Create category'}</Button></form></AdminCard><AdminCard title={id?'Kategori saat ini':'Current categories'}>{busy?<p role="status">Loading…</p>:rows.length===0?<AdminEmpty>{id?'Belum ada kategori.':'No categories.'}</AdminEmpty>:<ul className="space-y-2">{rows.map(c=><li key={c.category_id} className="flex flex-wrap items-center justify-between gap-3 rounded border border-[var(--color-border)] p-3"><div className="min-w-0"><b>{id?c.label_id:c.label_en}</b><p className="text-sm">{c.label_id} / {c.label_en}</p><p className="break-all font-mono text-xs">{c.code} · {c.category_id} · #{c.display_order}</p></div><div className="flex items-center gap-2"><AdminStatus value={c.active?'ACTIVE':'INACTIVE'}/><Button variant="secondary" disabled={!online||working} onClick={()=>void toggle(c)}>{c.active?(id?'Nonaktifkan':'Deactivate'):(id?'Aktifkan':'Activate')}</Button></div></li>)}</ul>}</AdminCard></AdminPage>
}

export function AdminPackageVersionCreate({ packageId }: { packageId:string }) {
 const {locale,id}=useCopy(); const online=useAdminOnline(); const [price,setPrice]=useState('');const [quota,setQuota]=useState('');const [key,setKey]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState<number>();const [ok,setOk]=useState(false);
 function payload(){return {price_amount:Number(price),currency:'IDR',quota_total:Number(quota)} satisfies PackageVersionCreateRequest}
 function intentKey(){if(!key)setKey(createUuidV7());return key||createUuidV7()}
 async function submit(e:React.FormEvent){e.preventDefault();if(!online||busy)return;setBusy(true);setError(undefined);setOk(false);try{const k=intentKey();const r=await postApiV1AdminPackagesPackageIdVersions(packageId,payload(),{headers:{...(await adminCsrfHeaders()),'Idempotency-Key':k}});if(r.status===201){setKey('');setOk(true)}else{setError(r.status);if(r.status===422)setKey('')}}catch{setError(0)}finally{setBusy(false)}}
 return <AdminPage title={id?'Buat versi paket':'Create package version'} description={id?'Versi sebelumnya tetap utuh. Retry ambigu memakai kunci intent yang sama; payload yang berubah memulai intent baru.':'Previous versions remain unchanged. Ambiguous retries reuse the same intent key; changing the payload starts a new intent.'}><AdminOfflineNote online={online} locale={locale}/><AdminCard><form onSubmit={e=>void submit(e)} className="max-w-2xl space-y-4"><AdminField label={id?'Harga (IDR)':'Price (IDR)'}><input type="number" min="0" step="1" required className={adminInputClass} value={price} onChange={e=>{if(e.target.value!==price)setKey('');setPrice(e.target.value)}}/></AdminField><AdminField label={id?'Kuota total':'Total quota'}><input type="number" min="1" max="10000" step="1" required className={adminInputClass} value={quota} onChange={e=>{if(e.target.value!==quota)setKey('');setQuota(e.target.value)}}/></AdminField><Button type="submit" disabled={!online||busy||!price||!quota} loading={busy}>{id?'Buat versi immutable':'Create immutable version'}</Button></form>{ok&&<div className="mt-4"><AdminFeedback kind="status">{id?'Versi baru dibuat oleh server.':'New version created by the server.'}</AdminFeedback></div>}{error!==undefined&&<div className="mt-4"><AdminFeedback>{error===409?(id?'Konflik versi saat ini. Muat ulang katalog.':'Version conflict. Reload the catalog.'):`${error===0?'Network':`HTTP ${error}`}. ${id?'Permintaan belum dianggap berhasil.':'The request was not treated as successful.'}`}</AdminFeedback></div>}</AdminCard></AdminPage>
}

export function AdminConfigs() {
 const {locale,id}=useCopy();const online=useAdminOnline();const [rows,setRows]=useState<OperationalConfig[]>([]);const [values,setValues]=useState<Record<string,string>>({});const [busy,setBusy]=useState(true);const [working,setWorking]=useState('');const [error,setError]=useState<number>();const [notice,setNotice]=useState('');
 async function load(){setBusy(true);setError(undefined);try{const r=await getApiV1AdminOperationalConfigs({limit:100});if(r.status===200){setRows(r.data.data);setValues(Object.fromEntries(r.data.data.map(c=>[c.config_key,typeof c.typed_value==='string'?c.typed_value:JSON.stringify(c.typed_value)])))}else setError(r.status)}catch{setError(0)}finally{setBusy(false)}}
 // eslint-disable-next-line react-hooks/set-state-in-effect -- start the initial server read after mount
 useEffect(()=>{void load()},[]);
 async function save(c:OperationalConfig){setWorking(c.config_key);setError(undefined);setNotice('');let typed:unknown=values[c.config_key];if(c.value_type==='INTEGER'||c.value_type==='NUMBER')typed=Number(typed);if(c.value_type==='BOOLEAN')typed=typed==='true';try{const r=await patchApiV1AdminOperationalConfigsKey(c.config_key,{expected_version:c.version,typed_value:typed},{headers:await adminCsrfHeaders()});if(r.status===200){setNotice(id?'Konfigurasi diperbarui dari respons server.':'Configuration updated from the server response.');await load()}else if(r.status===409){setError(409);setNotice(id?'Nilai berubah. Konfigurasi terkini sudah dimuat ulang.':'The value changed. Current configuration has been reloaded.');await load()}else setError(r.status)}catch{setError(0)}finally{setWorking('')}}
 return <AdminPage title={id?'Konfigurasi operasional':'Operational configuration'} description={id?'Hanya nilai bertipe yang diizinkan server dan ditandai dapat diedit yang dapat diubah. Aturan produk inti tetap terkunci.':'Only typed values allowlisted by the server and explicitly marked editable can change. Core product rules remain locked.'}><AdminOfflineNote online={online} locale={locale}/>{notice&&<AdminFeedback kind="status">{notice}</AdminFeedback>}{error!==undefined&&<AdminError locale={locale} status={error} retry={()=>void load()}/ >}{busy?<p role="status">{id?'Memuat konfigurasi…':'Loading configuration…'}</p>:rows.length===0?<AdminEmpty>{id?'Tidak ada konfigurasi yang dapat ditampilkan.':'No configuration entries are available.'}</AdminEmpty>:rows.map(c=><AdminCard key={c.config_key} title={c.display_name}><p className="mb-3 text-sm text-[var(--color-muted-foreground)]">{c.description}</p><div className="grid gap-3 sm:grid-cols-2"><p className="text-xs">{id?'Kunci':'Key'}: <code>{c.config_key}</code><br/>v{c.version} · {formatAdminDate(c.updated_at,locale)}</p>{!c.editable?<p className="text-sm font-semibold">{id?'Terkunci · aturan produk':'Locked · product rule'}</p>:<div className="space-y-2"><AdminField label={`${id?'Nilai':'Value'} · ${c.value_type}`}>
 {c.allowed_values?.length?<select className={adminInputClass} value={values[c.config_key]??''} onChange={e=>setValues(v=>({...v,[c.config_key]:e.target.value}))}>{c.allowed_values.map(v=><option key={String(v)} value={String(v)}>{String(v)}</option>)}</select>:c.value_type==='BOOLEAN'?<select className={adminInputClass} value={values[c.config_key]??'false'} onChange={e=>setValues(v=>({...v,[c.config_key]:e.target.value}))}><option value="true">true</option><option value="false">false</option></select>:<input type={c.value_type==='STRING'?'text':'number'} min={c.minimum??undefined} max={c.maximum??undefined} className={adminInputClass} value={values[c.config_key]??''} onChange={e=>setValues(v=>({...v,[c.config_key]:e.target.value}))}/>}</AdminField><Button variant="secondary" disabled={!online||!!working} loading={working===c.config_key} onClick={()=>void save(c)}>{id?'Simpan versi ini':'Save this version'}</Button></div>}</div></AdminCard>)}</AdminPage>
}

export function AdminIssues(){
 const {locale,id}=useCopy();const [rows,setRows]=useState<OperationalIssue[]>([]);const [cursor,setCursor]=useState<string|null>(null);const [more,setMore]=useState(false);const [status,setStatus]=useState('');const [busy,setBusy]=useState(true);const [error,setError]=useState<number>();
 async function load(next?:string,s=status){setBusy(true);setError(undefined);try{const r=await getApiV1AdminIssues({limit:25,...(next?{cursor:next}:{}),...(s?{status:s as never}:{})});if(r.status===200){setRows(r.data.data);setCursor(r.data.meta.next_cursor??null);setMore(r.data.meta.has_more)}else setError(r.status)}catch{setError(0)}finally{setBusy(false)}}
 // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps -- start the initial server read after mount
 useEffect(()=>{void load()},[]);
 return <AdminPage title={id?'Isu operasional':'Operational issues'} description={id?'Ringkasan aman untuk triase; tidak ada stack trace, SQL, header, atau payload provider mentah.':'Safe summaries for triage; no stack traces, SQL, headers, or raw provider payloads.'}><AdminCard><div className="flex flex-wrap items-end gap-3"><AdminField label={id?'Status':'Status'}><select className={adminInputClass} value={status} onChange={e=>setStatus(e.target.value)}><option value="">{id?'Semua':'All'}</option>{['OPEN','ACKNOWLEDGED','RESOLVED'].map(s=><option key={s}>{s}</option>)}</select></AdminField><Button variant="secondary" onClick={()=>void load(undefined,status)}>{id?'Terapkan':'Apply'}</Button></div></AdminCard>{error!==undefined?<AdminError locale={locale} status={error} retry={()=>void load()}/>:<AdminCard title={id?'Hasil':'Results'}>{busy&&<p role="status">{id?'Memuat isu…':'Loading issues…'}</p>}{!busy&&rows.length===0?<AdminEmpty>{id?'Tidak ada isu.':'No issues.'}</AdminEmpty>:<div className="space-y-2">{rows.map(i=><Link key={i.issue_id} href={`/admin/issues/${encodeURIComponent(i.issue_id)}`} className="block rounded border border-[var(--color-border)] p-3 hover:bg-[var(--color-muted)]"><div className="flex flex-wrap justify-between gap-2"><b>{i.summary}</b><AdminStatus value={i.status}/></div><p className="mt-1 text-xs">{i.severity} · {i.issue_type} · {i.error_code??'—'}</p><p className="break-all font-mono text-xs">{i.issue_id}</p></Link>)}</div>}<AdminPagination hasMore={more} cursor={cursor} busy={busy} locale={locale} onNext={()=>cursor&&void load(cursor)}/></AdminCard>}</AdminPage>
}

export function AdminIssueDetail({issueId}:{issueId:string}){
 const {locale,id}=useCopy();const online=useAdminOnline();const [issue,setIssue]=useState<OperationalIssue|null>(null);const [busy,setBusy]=useState(true);const [working,setWorking]=useState(false);const [error,setError]=useState<number>();const [reason,setReason]=useState('');const [confirm,setConfirm]=useState(false);const [action,setAction]=useState<'ack'|'resolve'>('ack');
 async function load(){setBusy(true);setError(undefined);try{const r=await getApiV1AdminIssuesIssueId(issueId);if(r.status===200)setIssue(r.data.data);else setError(r.status)}catch{setError(0)}finally{setBusy(false)}}
 // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps -- reload when the route issue changes
 useEffect(()=>{void load()},[issueId]);
 async function mutate(){setWorking(true);try{const h={headers:await adminCsrfHeaders()};const r=action==='ack'?await postApiV1AdminIssuesIssueIdAcknowledge(issueId,h):await postApiV1AdminIssuesIssueIdResolve(issueId,{reason:reason.trim()},h);if(r.status===200){setIssue(r.data.data);setReason('')}else setError(r.status)}catch{setError(0)}finally{setWorking(false);setConfirm(false)}}
 return <AdminPage title={id?'Detail isu':'Issue detail'} description={id?'Status perubahan selalu berasal dari server. Tidak ada tindakan menghapus isu atau mengubah log mentah.':'State changes always come from the server. There is no action to delete issues or alter raw logs.'}>{error!==undefined&&<AdminError locale={locale} status={error} retry={()=>void load()}/ >}{busy?<p role="status">Loading…</p>:!issue?<AdminEmpty>Not found.</AdminEmpty>:<><AdminCard title={issue.summary}><dl className="grid gap-3 sm:grid-cols-2"><div><dt>Status</dt><dd><AdminStatus value={issue.status}/></dd></div><div><dt>{id?'Tingkat':'Severity'}</dt><dd>{issue.severity}</dd></div><div><dt>{id?'Jenis':'Type'}</dt><dd>{issue.issue_type}</dd></div><div><dt>Error code</dt><dd>{issue.error_code??'—'}</dd></div><div><dt>{id?'Entitas terkait':'Related entity'}</dt><dd>{issue.related_entity_type??'—'} · {issue.related_entity_id??'—'}</dd></div><div><dt>{id?'Dibuat':'Created'}</dt><dd>{formatAdminDate(issue.created_at,locale)}</dd></div></dl></AdminCard><AdminCard title={id?'Tindakan triase':'Triage actions'}><div className="flex flex-wrap gap-2"><Button variant="secondary" disabled={!online||working||issue.status!=='OPEN'} onClick={()=>{setAction('ack');setConfirm(true)}}>{id?'Tanggapi':'Acknowledge'}</Button><AdminField label={id?'Alasan penyelesaian':'Resolution reason'}><input className={adminInputClass} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></AdminField><Button disabled={!online||working||issue.status==='RESOLVED'||!reason.trim()} onClick={()=>{setAction('resolve');setConfirm(true)}}>{id?'Selesaikan':'Resolve'}</Button></div></AdminCard></>}<ConfirmDialog open={confirm} title={action==='ack'?(id?'Tanggapi isu?':'Acknowledge issue?'):(id?'Selesaikan isu?':'Resolve issue?')} description={id?'Perubahan akan dicatat dan status terbaru akan berasal dari server.':'The change will be audited and the latest status will come from the server.'} confirmLabel={id?'Konfirmasi':'Confirm'} cancelLabel={id?'Batal':'Cancel'} onCancel={()=>setConfirm(false)} onConfirm={()=>void mutate()} disabled={working||!online}/></AdminPage>
}

export function AdminAudit(){
 const {locale,id}=useCopy();const [rows,setRows]=useState<AdminAuditLogSummary[]>([]);const [cursor,setCursor]=useState<string|null>(null);const [more,setMore]=useState(false);const [busy,setBusy]=useState(true);const [error,setError]=useState<number>();
 async function load(next?:string){setBusy(true);setError(undefined);try{const r=await getApiV1AdminAuditLogs({limit:50,...(next?{cursor:next}:{})});if(r.status===200){setRows(r.data.data);setCursor(r.data.meta.next_cursor??null);setMore(r.data.meta.has_more)}else setError(r.status)}catch{setError(0)}finally{setBusy(false)}}
 // eslint-disable-next-line react-hooks/set-state-in-effect -- start the initial server read after mount
 useEffect(()=>{void load()},[]);
 return <AdminPage title={id?'Log audit':'Audit log'} description={id?'Log append-only dan hanya-baca. Nilai sensitif tidak ditampilkan.':'Append-only, read-only records. Sensitive values are omitted.'}>{error!==undefined?<AdminError locale={locale} status={error} retry={()=>void load()}/>:<AdminCard>{busy&&<p role="status">Loading…</p>}{!busy&&!rows.length?<AdminEmpty>{id?'Belum ada catatan audit.':'No audit records.'}</AdminEmpty>:<div className="space-y-2">{rows.map(a=><Link key={a.audit_id} href={`/admin/audit/${encodeURIComponent(a.audit_id)}`} className="block min-w-0 rounded border border-[var(--color-border)] p-3 text-sm hover:bg-[var(--color-muted)]"><div className="flex flex-wrap justify-between gap-2"><b>{a.action} · {a.object_type}</b><AdminStatus value={a.result}/></div><p className="mt-1 break-words">{a.safe_change_summary}</p><p className="mt-2 break-all font-mono text-xs">{a.audit_id} · {a.actor_type}:{a.actor_id??'—'} · {a.object_ref??'—'}</p><p className="text-xs text-[var(--color-muted-foreground)]">{formatAdminDate(a.created_at,locale)} · request {a.request_id??'—'}</p></Link>)}</div>}<AdminPagination hasMore={more} cursor={cursor} busy={busy} locale={locale} onNext={()=>cursor&&void load(cursor)}/></AdminCard>}</AdminPage>
}

export function AdminAuditDetail({auditId}:{auditId:string}){
 const {locale,id}=useCopy();const [entry,setEntry]=useState<AdminAuditLogSummary|null>(null);const [busy,setBusy]=useState(true);const [error,setError]=useState<number>();
 async function load(){setBusy(true);setError(undefined);try{const r=await getApiV1AdminAuditLogsAuditId(auditId);if(r.status===200)setEntry(r.data.data.summary);else setError(r.status)}catch{setError(0)}finally{setBusy(false)}}
 // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps -- reload when the audit route changes
 useEffect(()=>{void load()},[auditId]);
 return <AdminPage title={id?'Detail audit':'Audit detail'} description={id?'Detail ini hanya-baca dan menampilkan konteks aman yang telah disaring.':'This detail is read-only and displays only redacted safe context.'}>{error!==undefined?<AdminError locale={locale} status={error} retry={()=>void load()}/>:busy?<p role="status">{id?'Memuat catatan…':'Loading record…'}</p>:!entry?<AdminEmpty>{id?'Catatan tidak ditemukan.':'Record not found.'}</AdminEmpty>:<AdminCard title={`${entry.action} · ${entry.object_type}`}><dl className="grid gap-4 text-sm sm:grid-cols-2"><div><dt>ID</dt><dd className="break-all font-mono">{entry.audit_id}</dd></div><div><dt>{id?'Hasil':'Result'}</dt><dd><AdminStatus value={entry.result}/></dd></div><div><dt>{id?'Aktor':'Actor'}</dt><dd>{entry.actor_type} · {entry.actor_id??'—'}</dd></div><div><dt>{id?'Album':'Album'}</dt><dd className="break-all font-mono">{entry.album_id??'—'}</dd></div><div><dt>{id?'Objek':'Object'}</dt><dd>{entry.object_type} · {entry.object_ref??'—'}</dd></div><div><dt>{id?'Waktu':'Time'}</dt><dd>{formatAdminDate(entry.created_at,locale)}</dd></div><div><dt>Request ID</dt><dd className="break-all font-mono">{entry.request_id??'—'}</dd></div><div className="sm:col-span-2"><dt>{id?'Ringkasan perubahan':'Change summary'}</dt><dd className="break-words">{entry.safe_change_summary}</dd></div></dl></AdminCard>}</AdminPage>
}

export function AdminRoster(){
 const {locale,id}=useCopy();const [rows,setRows]=useState<AdminRosterEntry[]>([]);const [cursor,setCursor]=useState<string|null>(null);const [more,setMore]=useState(false);const [busy,setBusy]=useState(true);const [error,setError]=useState<number>();
 async function load(next?:string){setBusy(true);setError(undefined);try{const r=await getApiV1AdminAdmins({limit:25,...(next?{cursor:next}:{})});if(r.status===200){setRows(r.data.data);setCursor(r.data.meta.next_cursor??null);setMore(r.data.meta.has_more)}else setError(r.status)}catch{setError(0)}finally{setBusy(false)}}
 // eslint-disable-next-line react-hooks/set-state-in-effect -- start the initial server read after mount
 useEffect(()=>{void load()},[]);
 return <AdminPage title={id?'Roster Admin':'Admin roster'} description={id?'Roster ini hanya-baca. Provisioning dan reset akses dikelola melalui proses operator di luar dashboard.':'This roster is read-only. Provisioning and access resets are managed by operators outside the dashboard.'}>{error!==undefined?<AdminError locale={locale} status={error} retry={()=>void load()}/>:<AdminCard>{busy&&<p role="status">Loading…</p>}{!busy&&!rows.length?<AdminEmpty>{id?'Tidak ada entri.':'No entries.'}</AdminEmpty>:<ul className="space-y-3">{rows.map(a=><li key={a.admin_user_id} className="flex flex-wrap items-start justify-between gap-3 rounded border border-[var(--color-border)] p-3"><div className="min-w-0"><b className="block break-all">{a.display_name??a.email}</b><p className="break-all text-sm">{a.email}</p><code className="break-all text-xs">{a.admin_user_id}</code><p className="text-xs text-[var(--color-muted-foreground)]">{id?'Diberikan':'Granted'} {formatAdminDate(a.granted_at,locale)} · {id?'Sesi terakhir':'Last session'} {formatAdminDate(a.last_session_at,locale)}</p></div><AdminStatus value={a.grant_status}/></li>)}</ul>}<AdminPagination hasMore={more} cursor={cursor} busy={busy} locale={locale} onNext={()=>cursor&&void load(cursor)}/></AdminCard>}</AdminPage>
}
