'use client';

import Link from 'next/link';
import { useLocale, useTranslations } from 'next-intl';
import { useEffect, useRef, useState } from 'react';
import { Button } from '@/components/ui/button';
import { ConfirmDialog } from '@/components/ui/confirm-dialog';
import {
  getApiV1AdminPayments, getApiV1AdminPaymentsTransactionId, postApiV1AdminPaymentsTransactionIdReconcile,
  getApiV1AdminPackages, postApiV1AdminPackagesPackageIdVersions, getApiV1AdminOperationalConfigs, patchApiV1AdminOperationalConfigsKey,
  getApiV1AdminIssues, getApiV1AdminIssuesIssueId, postApiV1AdminIssuesIssueIdAcknowledge, postApiV1AdminIssuesIssueIdResolve,
  getApiV1AdminAuditLogs, getApiV1AdminAuditLogsAuditId, getApiV1AdminAdmins, getApiV1AdminEventCategories, postApiV1AdminEventCategories, patchApiV1AdminEventCategoriesCategoryId,
  patchApiV1AdminPackageVersionsVersionIdSaleStatus,
} from '@/lib/api/admin-browser';
import type { AdminPackage, AdminPackageVersion, AdminPaymentDiagnosis, AdminAuditLogSummary, AdminRosterEntry, EventCategory, OperationalConfig, OperationalIssue, PaymentTransaction, PackageVersionCreateRequest } from '@/lib/api/generated/index.schemas';
import { createUuidV7 } from '@/features/guest/lib/idempotency';
import { AdminCard, AdminEmpty, AdminError, AdminFeedback, AdminField, AdminOfflineNote, AdminPage, AdminPagination, AdminStatus, adminCsrfHeaders, adminInputClass, formatAdminDate, formatAdminNumber, type AdminLocale, useAdminOnline } from './common';

function useCopy() { const locale = (useLocale() === 'en' ? 'en' : 'id') as AdminLocale; const t = useTranslations('admin.legacyCopy'); const commonT = useTranslations('admin.common'); return { locale, id: locale === 'id', t, commonT }; }

export function AdminPayments() {
  const { locale, t } = useCopy(); const [rows, setRows] = useState<PaymentTransaction[]>([]); const [cursor, setCursor] = useState<string | null>(null); const [more, setMore] = useState(false); const [busy, setBusy] = useState(true); const [error, setError] = useState<number>();
  async function load(next?: string) { setBusy(true); setError(undefined); try { const r = await getApiV1AdminPayments({ limit: 25, ...(next ? { cursor: next } : {}) }); if (r.status === 200) { setRows(r.data.data); setCursor(r.data.meta.next_cursor ?? null); setMore(r.data.meta.has_more); } else setError(r.status); } catch { setError(0); } finally { setBusy(false); } }
  // eslint-disable-next-line react-hooks/set-state-in-effect -- start the initial server read after mount
  useEffect(() => { void load(); }, []);
  return <AdminPage title={t('data_payments')} description={t('data_transaction_diagnosis_and_provider')}>{error !== undefined ? <AdminError locale={locale} status={error} retry={() => void load()} /> : <AdminCard title={t('data_transactions')}>
    {busy && <p role="status">{t('data_loading_transactions')}</p>}{!busy && rows.length === 0 ? <AdminEmpty>{t('data_no_transactions')}</AdminEmpty> : <div className="space-y-2">{rows.map(p => <Link key={p.transaction_id} href={`/admin/payments/${encodeURIComponent(p.transaction_id)}`} className="grid gap-2 rounded-[var(--radius-md)] border border-[var(--color-border)] p-3 text-sm hover:bg-[var(--color-muted)] sm:grid-cols-[minmax(0,1fr)_auto_auto] sm:items-center"><span className="min-w-0"><b className="block">{p.package_name_snapshot} · {p.type}</b><span className="break-all font-mono text-xs text-[var(--color-muted-foreground)]">{p.transaction_id}</span></span><AdminStatus value={p.status} /><span className="whitespace-nowrap tabular-nums">{new Intl.NumberFormat(locale,{style:'currency',currency:p.currency}).format(p.amount)}</span></Link>)}</div>}
    <AdminPagination hasMore={more} cursor={cursor} busy={busy} locale={locale} onNext={() => cursor && void load(cursor)} />
  </AdminCard>}</AdminPage>;
}

export function AdminPaymentDetail({ transactionId }: { transactionId: string }) {
  const { locale, t, commonT } = useCopy(); const online = useAdminOnline(); const [data, setData] = useState<AdminPaymentDiagnosis | null>(null); const [busy, setBusy] = useState(true); const [error, setError] = useState<number>(); const [working, setWorking] = useState(false); const [confirm, setConfirm] = useState(false); const [message, setMessage] = useState('');
  async function load() { setBusy(true); setError(undefined); try { const r = await getApiV1AdminPaymentsTransactionId(transactionId); if (r.status === 200) setData(r.data.data); else setError(r.status); } catch { setError(0); } finally { setBusy(false); } }
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps -- reload when the route transaction changes
  useEffect(() => { void load(); }, [transactionId]);
  async function reconcile() { setWorking(true); setError(undefined); setMessage(''); try { const r = await postApiV1AdminPaymentsTransactionIdReconcile(transactionId, { headers: await adminCsrfHeaders() }); if (r.status === 200) { setData(r.data.data); setMessage(t('data_latest_provider_response_and_trans')); } else setError(r.status); } catch { setError(0); } finally { setWorking(false); setConfirm(false); } }
  const p = data?.transaction;
  return <AdminPage title={t('data_payment_diagnosis')} description={t('data_reconciliation_only_requests_a_pro')}>{error !== undefined ? <AdminError locale={locale} status={error} retry={() => void load()} /> : busy ? <p role="status">{t('data_loading_diagnosis')}</p> : !data || !p ? <AdminEmpty>{t('data_transaction_not_found')}</AdminEmpty> : <>
    <AdminCard title={p.package_name_snapshot}><dl className="grid gap-4 text-sm sm:grid-cols-2"><div><dt>{t('data_transaction_id')}</dt><dd className="break-all font-mono">{p.transaction_id}</dd></div><div><dt>{commonT('album')}</dt><dd className="break-all font-mono">{p.album_id}</dd></div><div><dt>{t('data_server_status')}</dt><dd><AdminStatus value={p.status} /></dd></div><div><dt>{t('data_type')}</dt><dd>{p.type}</dd></div><div><dt>{t('data_snapshot_amount')}</dt><dd>{new Intl.NumberFormat(locale,{style:'currency',currency:p.currency}).format(p.amount)}</dd></div><div><dt>{t('data_snapshot_target_quota')}</dt><dd>{formatAdminNumber(p.target_quota_total_snapshot, locale)}</dd></div><div><dt>{t('data_payment_cutoff')}</dt><dd>{formatAdminDate(p.payment_cutoff_at, locale)}</dd></div><div><dt>{t('data_current_entitlement')}</dt><dd>{data.entitlement ? JSON.stringify(data.entitlement) : (t('data_no_projection'))}</dd></div></dl></AdminCard>
    <AdminCard title={t('data_provider_receipt_diagnostics')}>{data.receipt_diagnostics.length ? <ul className="space-y-3">{data.receipt_diagnostics.map(x => <li key={x.receipt_id} className="rounded-[var(--radius-md)] border border-[var(--color-border)] p-3 text-sm"><p className="font-semibold">{x.source} · {x.provider_state ?? '—'}</p><p>{t('data_signature_verified')}: {x.signature_verified ? t('data_yes') : t('data_no')} · {x.process_result ?? '—'} · {x.error_code ?? '—'}</p><p className="text-xs text-[var(--color-muted-foreground)]">{formatAdminDate(x.received_at, locale)} · {formatAdminDate(x.processed_at, locale)}</p></li>)}</ul> : <AdminEmpty>{t('data_no_provider_receipt_summaries')}</AdminEmpty>}
      <p className="mt-4 text-sm">{t('data_available_action_provider_re_check')}</p><Button className="mt-3" disabled={!online || working || !data.can_reconcile} loading={working} onClick={() => setConfirm(true)}>{t('data_re_check_with_provider')}</Button>
      {message && <div className="mt-3"><AdminFeedback kind="status">{message}</AdminFeedback></div>}{error !== undefined && <div className="mt-3"><AdminFeedback>{error === 503 ? (t('data_provider_or_supporting_service_is')) : `${error ? t('data_http_status',{status:error}) : t('data_network_error')}`}</AdminFeedback></div>}
    </AdminCard></>}
    <ConfirmDialog open={confirm} title={t('data_re_check_provider_status')} description={t('data_this_requests_the_provider_state_a')} confirmLabel={t('data_continue')} cancelLabel={t('data_cancel')} onCancel={() => setConfirm(false)} onConfirm={() => void reconcile()} disabled={working || !online} />
  </AdminPage>;
}

export function AdminPackages() {
  const { locale, t } = useCopy(); const online=useAdminOnline(); const [rows,setRows]=useState<AdminPackage[]>([]); const [cursor,setCursor]=useState<string|null>(null); const [more,setMore]=useState(false); const [error,setError]=useState<number>(); const [busy,setBusy]=useState(true); const [pendingSale,setPendingSale]=useState<{version:AdminPackageVersion; enabled:boolean}|null>(null); const [savingSale,setSavingSale]=useState(false);
  async function load(next?:string){setBusy(true);setError(undefined);try{const r=await getApiV1AdminPackages({limit:25,...(next?{cursor:next}:{})});if(r.status===200){setRows(r.data.data);setCursor(r.data.meta.next_cursor??null);setMore(r.data.meta.has_more)}else setError(r.status)}catch{setError(0)}finally{setBusy(false)}}
  // eslint-disable-next-line react-hooks/set-state-in-effect -- start the initial server read after mount
  useEffect(()=>{void load()},[]);
  async function toggleSale(){if(!pendingSale||!online)return;setSavingSale(true);setError(undefined);try{const r=await patchApiV1AdminPackageVersionsVersionIdSaleStatus(pendingSale.version.package_version_id,{sale_enabled:pendingSale.enabled},{headers:await adminCsrfHeaders()});if(r.status===200){setPendingSale(null);await load()}else setError(r.status)}catch{setError(0)}finally{setSavingSale(false)}}
  return <AdminPage title={t('data_package_catalog')} description={t('data_historical_versions_are_immutable')}>{error!==undefined?<AdminError locale={locale} status={error} retry={()=>void load()}/>:<>
    {busy&&<p role="status">{t('data_loading_catalog')}</p>}{!busy&&rows.length===0?<AdminEmpty>{t('data_no_packages')}</AdminEmpty>:rows.map(pkg=><AdminCard key={pkg.package_id} title={`${pkg.name} · ${pkg.code}`}><p className="break-all font-mono text-xs">{pkg.package_id}</p><div className="mt-3 space-y-2">{pkg.versions.map(v=><div key={v.package_version_id} className="grid gap-2 rounded border border-[var(--color-border)] p-3 text-sm sm:grid-cols-[minmax(0,1fr)_auto_auto_auto] sm:items-center"><span className="break-all font-mono text-xs">{v.package_version_id}</span><span>{new Intl.NumberFormat(locale,{style:'currency',currency:v.currency}).format(v.price_amount)}</span><span>{formatAdminNumber(v.quota_total,locale)} {t('data_photos')}</span><div className="flex items-center gap-2"><AdminStatus value={v.sale_enabled?'SALE ENABLED':'RETIRED'}/><Button variant="secondary" disabled={!online} onClick={()=>setPendingSale({version:v,enabled:!v.sale_enabled})}>{v.sale_enabled?(t('data_retire')):(t('data_enable'))}</Button></div></div>)}</div><Link className="mt-4 inline-flex min-h-11 items-center font-semibold underline" href={`/admin/catalog/packages/${encodeURIComponent(pkg.package_id)}/versions/new`}>{t('data_create_new_version')}</Link></AdminCard>)}
    <Link className="inline-flex min-h-11 items-center font-semibold underline" href="/admin/catalog/categories">{t('data_manage_event_categories')}</Link>
    <AdminPagination hasMore={more} cursor={cursor} busy={busy} locale={locale} onNext={()=>cursor&&void load(cursor)}/></>}<ConfirmDialog open={!!pendingSale} title={pendingSale?.enabled?(t('data_enable_sales')):(t('data_retire_this_version'))} description={t('data_this_only_changes_availability_for')} confirmLabel={t('data_confirm')} cancelLabel={t('data_cancel')} destructive={!pendingSale?.enabled} onCancel={()=>setPendingSale(null)} onConfirm={()=>void toggleSale()} disabled={savingSale||!online}/></AdminPage>;
}

export function AdminCategories(){
 const { locale, id, t, commonT } = useCopy();const online=useAdminOnline();const [rows,setRows]=useState<EventCategory[]>([]);const [busy,setBusy]=useState(true);const [working,setWorking]=useState(false);const [error,setError]=useState<number>();const [code,setCode]=useState('');const [labelId,setLabelId]=useState('');const [labelEn,setLabelEn]=useState('');const [order,setOrder]=useState('0');const [notice,setNotice]=useState('');
 async function load(){setBusy(true);setError(undefined);try{const r=await getApiV1AdminEventCategories({limit:100});if(r.status===200)setRows(r.data.data);else setError(r.status)}catch{setError(0)}finally{setBusy(false)}}
 // eslint-disable-next-line react-hooks/set-state-in-effect -- start the initial server read after mount
 useEffect(()=>{void load()},[]);
 async function create(e:React.FormEvent){e.preventDefault();if(!online||working)return;setWorking(true);setError(undefined);try{const r=await postApiV1AdminEventCategories({code:code.trim(),label_id:labelId.trim(),label_en:labelEn.trim(),display_order:Number(order),active:true},{headers:await adminCsrfHeaders()});if(r.status===201){setCode('');setLabelId('');setLabelEn('');setOrder('0');await load()}else setError(r.status)}catch{setError(0)}finally{setWorking(false)}}
 async function toggle(c:EventCategory){setWorking(true);setError(undefined);try{const r=await patchApiV1AdminEventCategoriesCategoryId(c.category_id,{active:!c.active},{headers:await adminCsrfHeaders()});if(r.status===200){setNotice(t('data_category_status_updated_its_identi'));await load()}else setError(r.status)}catch{setError(0)}finally{setWorking(false)}}
 return <AdminPage title={t('data_event_categories')} description={t('data_categories_can_be_deactivated_with')}><AdminOfflineNote online={online} locale={locale}/>{error!==undefined&&<AdminError locale={locale} status={error} retry={()=>void load()}/ >}{notice&&<AdminFeedback kind="status">{notice}</AdminFeedback>}<AdminCard title={t('data_add_category')}><form onSubmit={e=>void create(e)} className="grid gap-3 sm:grid-cols-2"><AdminField label={commonT('code')}><input className={adminInputClass} maxLength={50} required value={code} onChange={e=>setCode(e.target.value)}/></AdminField><AdminField label={t('data_indonesian_label')}><input className={adminInputClass} maxLength={100} required value={labelId} onChange={e=>setLabelId(e.target.value)}/></AdminField><AdminField label={t('data_english_label')}><input className={adminInputClass} maxLength={100} required value={labelEn} onChange={e=>setLabelEn(e.target.value)}/></AdminField><AdminField label={t('data_display_order')}><input type="number" className={adminInputClass} required value={order} onChange={e=>setOrder(e.target.value)}/></AdminField><Button className="sm:col-span-2 sm:justify-self-start" disabled={!online||working} loading={working}>{t('data_create_category')}</Button></form></AdminCard><AdminCard title={t('data_current_categories')}>{busy?<p role="status">{t('data_loading_short')}</p>:rows.length===0?<AdminEmpty>{t('data_no_categories')}</AdminEmpty>:<ul className="space-y-2">{rows.map(c=><li key={c.category_id} className="flex flex-wrap items-center justify-between gap-3 rounded border border-[var(--color-border)] p-3"><div className="min-w-0"><b>{id?c.label_id:c.label_en}</b><p className="text-sm">{c.label_id} / {c.label_en}</p><p className="break-all font-mono text-xs">{c.code} · {c.category_id} · #{c.display_order}</p></div><div className="flex items-center gap-2"><AdminStatus value={c.active?'ACTIVE':'INACTIVE'}/><Button variant="secondary" disabled={!online||working} onClick={()=>void toggle(c)}>{c.active?(t('data_deactivate')):(t('data_activate'))}</Button></div></li>)}</ul>}</AdminCard></AdminPage>
}

export function AdminPackageVersionCreate({ packageId }: { packageId:string }) {
 const { locale, t } = useCopy(); const online=useAdminOnline(); const [price,setPrice]=useState('');const [quota,setQuota]=useState('');const intentRef=useRef<{fingerprint:string;key:string}|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState<number>();const [ok,setOk]=useState(false);
 function payload(){return {price_amount:Number(price),currency:'IDR',quota_total:Number(quota)} satisfies PackageVersionCreateRequest}
 function intentKey(requestPayload:PackageVersionCreateRequest){const fingerprint=JSON.stringify([packageId,requestPayload.price_amount,requestPayload.currency,requestPayload.quota_total]);if(intentRef.current?.fingerprint!==fingerprint)intentRef.current={fingerprint,key:createUuidV7()};return intentRef.current.key}
 async function submit(e:React.FormEvent){e.preventDefault();if(!online||busy)return;setBusy(true);setError(undefined);setOk(false);try{const requestPayload=payload();const k=intentKey(requestPayload);const r=await postApiV1AdminPackagesPackageIdVersions(packageId,requestPayload,{headers:{...(await adminCsrfHeaders()),'Idempotency-Key':k}});if(r.status===201){intentRef.current=null;setOk(true)}else{setError(r.status);if(r.status===422)intentRef.current=null}}catch{setError(0)}finally{setBusy(false)}}
 return <AdminPage title={t('data_create_package_version')} description={t('data_previous_versions_remain_unchanged')}><AdminOfflineNote online={online} locale={locale}/><AdminCard><form onSubmit={e=>void submit(e)} className="max-w-2xl space-y-4"><AdminField label={t('data_price_idr')}><input type="number" min="0" step="1" required className={adminInputClass} value={price} onChange={e=>{if(e.target.value!==price)intentRef.current=null;setPrice(e.target.value)}}/></AdminField><AdminField label={t('data_total_quota')}><input type="number" min="1" max="10000" step="1" required className={adminInputClass} value={quota} onChange={e=>{if(e.target.value!==quota)intentRef.current=null;setQuota(e.target.value)}}/></AdminField><Button type="submit" disabled={!online||busy||!price||!quota} loading={busy}>{t('data_create_immutable_version')}</Button></form>{ok&&<div className="mt-4"><AdminFeedback kind="status">{t('data_new_version_created_by_the_server')}</AdminFeedback></div>}{error!==undefined&&<div className="mt-4"><AdminFeedback>{error===409?(t('data_version_conflict_reload_the_catalo')):`${error===0?t('data_network_error'):t('data_http_status',{status:error})}. ${t('data_the_request_was_not_treated_as_suc')}`}</AdminFeedback></div>}</AdminCard></AdminPage>
}

export function AdminConfigs() {
 const { locale, t } = useCopy();const online=useAdminOnline();const [rows,setRows]=useState<OperationalConfig[]>([]);const [values,setValues]=useState<Record<string,string>>({});const [busy,setBusy]=useState(true);const [working,setWorking]=useState('');const [error,setError]=useState<number>();const [notice,setNotice]=useState('');
 async function load(){setBusy(true);setError(undefined);try{const r=await getApiV1AdminOperationalConfigs({limit:100});if(r.status===200){setRows(r.data.data);setValues(Object.fromEntries(r.data.data.map(c=>[c.config_key,typeof c.typed_value==='string'?c.typed_value:JSON.stringify(c.typed_value)])))}else setError(r.status)}catch{setError(0)}finally{setBusy(false)}}
 // eslint-disable-next-line react-hooks/set-state-in-effect -- start the initial server read after mount
 useEffect(()=>{void load()},[]);
 async function save(c:OperationalConfig){setWorking(c.config_key);setError(undefined);setNotice('');let typed:unknown=values[c.config_key];if(c.value_type==='INTEGER'||c.value_type==='NUMBER')typed=Number(typed);if(c.value_type==='BOOLEAN')typed=typed==='true';try{const r=await patchApiV1AdminOperationalConfigsKey(c.config_key,{expected_version:c.version,typed_value:typed},{headers:await adminCsrfHeaders()});if(r.status===200){setNotice(t('data_configuration_updated_from_the_ser'));await load()}else if(r.status===409){setError(409);setNotice(t('data_the_value_changed_current_configur'));await load()}else setError(r.status)}catch{setError(0)}finally{setWorking('')}}
 return <AdminPage title={t('data_operational_configuration')} description={t('data_only_typed_values_allowlisted_by_t')}><AdminOfflineNote online={online} locale={locale}/>{notice&&<AdminFeedback kind="status">{notice}</AdminFeedback>}{error!==undefined&&<AdminError locale={locale} status={error} retry={()=>void load()}/ >}{busy?<p role="status">{t('data_loading_configuration')}</p>:rows.length===0?<AdminEmpty>{t('data_no_configuration_entries_are_avail')}</AdminEmpty>:rows.map(c=><AdminCard key={c.config_key} title={c.display_name}><p className="mb-3 text-sm text-[var(--color-muted-foreground)]">{c.description}</p><div className="grid gap-3 sm:grid-cols-2"><p className="text-xs">{t('data_key')}: <code>{c.config_key}</code><br/>v{c.version} · {formatAdminDate(c.updated_at,locale)}</p>{!c.editable?<p className="text-sm font-semibold">{t('data_locked_product_rule')}</p>:<div className="space-y-2"><AdminField label={`${t('data_value')} · ${c.value_type}`}>
 {c.allowed_values?.length?<select className={adminInputClass} value={values[c.config_key]??''} onChange={e=>setValues(v=>({...v,[c.config_key]:e.target.value}))}>{c.allowed_values.map(v=><option key={String(v)} value={String(v)}>{String(v)}</option>)}</select>:c.value_type==='BOOLEAN'?<select className={adminInputClass} value={values[c.config_key]??'false'} onChange={e=>setValues(v=>({...v,[c.config_key]:e.target.value}))}><option value="true">true</option><option value="false">false</option></select>:<input type={c.value_type==='STRING'?'text':'number'} min={c.minimum??undefined} max={c.maximum??undefined} className={adminInputClass} value={values[c.config_key]??''} onChange={e=>setValues(v=>({...v,[c.config_key]:e.target.value}))}/>}</AdminField><Button variant="secondary" disabled={!online||!!working} loading={working===c.config_key} onClick={()=>void save(c)}>{t('data_save_this_version')}</Button></div>}</div></AdminCard>)}</AdminPage>
}

export function AdminIssues(){
 const { locale, t, commonT } = useCopy();const [rows,setRows]=useState<OperationalIssue[]>([]);const [cursor,setCursor]=useState<string|null>(null);const [more,setMore]=useState(false);const [status,setStatus]=useState('');const [busy,setBusy]=useState(true);const [error,setError]=useState<number>();
 async function load(next?:string,s=status){setBusy(true);setError(undefined);try{const r=await getApiV1AdminIssues({limit:25,...(next?{cursor:next}:{}),...(s?{status:s as never}:{})});if(r.status===200){setRows(r.data.data);setCursor(r.data.meta.next_cursor??null);setMore(r.data.meta.has_more)}else setError(r.status)}catch{setError(0)}finally{setBusy(false)}}
 // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps -- start the initial server read after mount
 useEffect(()=>{void load()},[]);
 return <AdminPage title={t('data_operational_issues')} description={t('data_safe_summaries_for_triage_no_stack')}><AdminCard><div className="flex flex-wrap items-end gap-3"><AdminField label={commonT('status')}><select className={adminInputClass} value={status} onChange={e=>setStatus(e.target.value)}><option value="">{t('data_all')}</option>{['OPEN','ACKNOWLEDGED','RESOLVED'].map(s=><option key={s}>{s}</option>)}</select></AdminField><Button variant="secondary" onClick={()=>void load(undefined,status)}>{t('data_apply')}</Button></div></AdminCard>{error!==undefined?<AdminError locale={locale} status={error} retry={()=>void load()}/>:<AdminCard title={t('data_results')}>{busy&&<p role="status">{t('data_loading_issues')}</p>}{!busy&&rows.length===0?<AdminEmpty>{t('data_no_issues')}</AdminEmpty>:<div className="space-y-2">{rows.map(i=><Link key={i.issue_id} href={`/admin/issues/${encodeURIComponent(i.issue_id)}`} className="block rounded border border-[var(--color-border)] p-3 hover:bg-[var(--color-muted)]"><div className="flex flex-wrap justify-between gap-2"><b>{i.summary}</b><AdminStatus value={i.status}/></div><p className="mt-1 text-xs">{i.severity} · {i.issue_type} · {i.error_code??'—'}</p><p className="break-all font-mono text-xs">{i.issue_id}</p></Link>)}</div>}<AdminPagination hasMore={more} cursor={cursor} busy={busy} locale={locale} onNext={()=>cursor&&void load(cursor)}/></AdminCard>}</AdminPage>
}

export function AdminIssueDetail({issueId}:{issueId:string}){
 const { locale, t, commonT } = useCopy();const online=useAdminOnline();const [issue,setIssue]=useState<OperationalIssue|null>(null);const [busy,setBusy]=useState(true);const [working,setWorking]=useState(false);const [error,setError]=useState<number>();const [reason,setReason]=useState('');const [confirm,setConfirm]=useState(false);const [action,setAction]=useState<'ack'|'resolve'>('ack');
 async function load(){setBusy(true);setError(undefined);try{const r=await getApiV1AdminIssuesIssueId(issueId);if(r.status===200)setIssue(r.data.data);else setError(r.status)}catch{setError(0)}finally{setBusy(false)}}
 // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps -- reload when the route issue changes
 useEffect(()=>{void load()},[issueId]);
 async function mutate(){setWorking(true);try{const h={headers:await adminCsrfHeaders()};const r=action==='ack'?await postApiV1AdminIssuesIssueIdAcknowledge(issueId,h):await postApiV1AdminIssuesIssueIdResolve(issueId,{reason:reason.trim()},h);if(r.status===200){setIssue(r.data.data);setReason('')}else setError(r.status)}catch{setError(0)}finally{setWorking(false);setConfirm(false)}}
 return <AdminPage title={t('data_issue_detail')} description={t('data_state_changes_always_come_from_the')}>{error!==undefined&&<AdminError locale={locale} status={error} retry={()=>void load()}/ >}{busy?<p role="status">{t('data_loading_short')}</p>:!issue?<AdminEmpty>{t('data_not_found')}</AdminEmpty>:<><AdminCard title={issue.summary}><dl className="grid gap-3 sm:grid-cols-2"><div><dt>{commonT('status')}</dt><dd><AdminStatus value={issue.status}/></dd></div><div><dt>{t('data_severity')}</dt><dd>{issue.severity}</dd></div><div><dt>{t('data_type')}</dt><dd>{issue.issue_type}</dd></div><div><dt>{t('data_error_code')}</dt><dd>{issue.error_code??'—'}</dd></div><div><dt>{t('data_related_entity')}</dt><dd>{issue.related_entity_type??'—'} · {issue.related_entity_id??'—'}</dd></div><div><dt>{t('data_created')}</dt><dd>{formatAdminDate(issue.created_at,locale)}</dd></div></dl></AdminCard><AdminCard title={t('data_triage_actions')}><div className="flex flex-wrap gap-2"><Button variant="secondary" disabled={!online||working||issue.status!=='OPEN'} onClick={()=>{setAction('ack');setConfirm(true)}}>{t('data_acknowledge')}</Button><AdminField label={t('data_resolution_reason')}><input className={adminInputClass} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></AdminField><Button disabled={!online||working||issue.status==='RESOLVED'||!reason.trim()} onClick={()=>{setAction('resolve');setConfirm(true)}}>{t('data_resolve')}</Button></div></AdminCard></>}<ConfirmDialog open={confirm} title={action==='ack'?(t('data_acknowledge_issue')):(t('data_resolve_issue'))} description={t('data_the_change_will_be_audited_and_the')} confirmLabel={t('data_confirm')} cancelLabel={t('data_cancel')} onCancel={()=>setConfirm(false)} onConfirm={()=>void mutate()} disabled={working||!online}/></AdminPage>
}

export function AdminAudit(){
 const { locale, t } = useCopy();const [rows,setRows]=useState<AdminAuditLogSummary[]>([]);const [cursor,setCursor]=useState<string|null>(null);const [more,setMore]=useState(false);const [busy,setBusy]=useState(true);const [error,setError]=useState<number>();
 async function load(next?:string){setBusy(true);setError(undefined);try{const r=await getApiV1AdminAuditLogs({limit:50,...(next?{cursor:next}:{})});if(r.status===200){setRows(r.data.data);setCursor(r.data.meta.next_cursor??null);setMore(r.data.meta.has_more)}else setError(r.status)}catch{setError(0)}finally{setBusy(false)}}
 // eslint-disable-next-line react-hooks/set-state-in-effect -- start the initial server read after mount
 useEffect(()=>{void load()},[]);
 return <AdminPage title={t('data_audit_log')} description={t('data_append_only_read_only_records_sens')}>{error!==undefined?<AdminError locale={locale} status={error} retry={()=>void load()}/>:<AdminCard>{busy&&<p role="status">{t('data_loading_short')}</p>}{!busy&&!rows.length?<AdminEmpty>{t('data_no_audit_records')}</AdminEmpty>:<div className="space-y-2">{rows.map(a=><Link key={a.audit_id} href={`/admin/audit/${encodeURIComponent(a.audit_id)}`} className="block min-w-0 rounded border border-[var(--color-border)] p-3 text-sm hover:bg-[var(--color-muted)]"><div className="flex flex-wrap justify-between gap-2"><b>{a.action} · {a.object_type}</b><AdminStatus value={a.result}/></div><p className="mt-1 break-words">{a.safe_change_summary}</p><p className="mt-2 break-all font-mono text-xs">{a.audit_id} · {a.actor_type}:{a.actor_id??'—'} · {a.object_ref??'—'}</p><p className="text-xs text-[var(--color-muted-foreground)]">{formatAdminDate(a.created_at,locale)} · {t('data_request')} {a.request_id??'—'}</p></Link>)}</div>}<AdminPagination hasMore={more} cursor={cursor} busy={busy} locale={locale} onNext={()=>cursor&&void load(cursor)}/></AdminCard>}</AdminPage>
}

export function AdminAuditDetail({auditId}:{auditId:string}){
 const { locale, t, commonT } = useCopy();const [entry,setEntry]=useState<AdminAuditLogSummary|null>(null);const [busy,setBusy]=useState(true);const [error,setError]=useState<number>();
 async function load(){setBusy(true);setError(undefined);try{const r=await getApiV1AdminAuditLogsAuditId(auditId);if(r.status===200)setEntry(r.data.data.summary);else setError(r.status)}catch{setError(0)}finally{setBusy(false)}}
 // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps -- reload when the audit route changes
 useEffect(()=>{void load()},[auditId]);
 return <AdminPage title={t('data_audit_detail')} description={t('data_this_detail_is_read_only_and_displ')}>{error!==undefined?<AdminError locale={locale} status={error} retry={()=>void load()}/>:busy?<p role="status">{t('data_loading_record')}</p>:!entry?<AdminEmpty>{t('data_record_not_found')}</AdminEmpty>:<AdminCard title={`${entry.action} · ${entry.object_type}`}><dl className="grid gap-4 text-sm sm:grid-cols-2"><div><dt>ID</dt><dd className="break-all font-mono">{entry.audit_id}</dd></div><div><dt>{t('data_result')}</dt><dd><AdminStatus value={entry.result}/></dd></div><div><dt>{t('data_actor')}</dt><dd>{entry.actor_type} · {entry.actor_id??'—'}</dd></div><div><dt>{commonT('album')}</dt><dd className="break-all font-mono">{entry.album_id??'—'}</dd></div><div><dt>{t('data_object')}</dt><dd>{entry.object_type} · {entry.object_ref??'—'}</dd></div><div><dt>{t('data_time')}</dt><dd>{formatAdminDate(entry.created_at,locale)}</dd></div><div><dt>{commonT('requestId')}</dt><dd className="break-all font-mono">{entry.request_id??'—'}</dd></div><div className="sm:col-span-2"><dt>{t('data_change_summary')}</dt><dd className="break-words">{entry.safe_change_summary}</dd></div></dl></AdminCard>}</AdminPage>
}

export function AdminRoster(){
 const { locale, t } = useCopy();const [rows,setRows]=useState<AdminRosterEntry[]>([]);const [cursor,setCursor]=useState<string|null>(null);const [more,setMore]=useState(false);const [busy,setBusy]=useState(true);const [error,setError]=useState<number>();
 async function load(next?:string){setBusy(true);setError(undefined);try{const r=await getApiV1AdminAdmins({limit:25,...(next?{cursor:next}:{})});if(r.status===200){setRows(r.data.data);setCursor(r.data.meta.next_cursor??null);setMore(r.data.meta.has_more)}else setError(r.status)}catch{setError(0)}finally{setBusy(false)}}
 // eslint-disable-next-line react-hooks/set-state-in-effect -- start the initial server read after mount
 useEffect(()=>{void load()},[]);
 return <AdminPage title={t('data_admin_roster')} description={t('data_this_roster_is_read_only_provision')}>{error!==undefined?<AdminError locale={locale} status={error} retry={()=>void load()}/>:<AdminCard>{busy&&<p role="status">{t('data_loading_short')}</p>}{!busy&&!rows.length?<AdminEmpty>{t('data_no_entries')}</AdminEmpty>:<ul className="space-y-3">{rows.map(a=><li key={a.admin_user_id} className="flex flex-wrap items-start justify-between gap-3 rounded border border-[var(--color-border)] p-3"><div className="min-w-0"><b className="block break-all">{a.display_name??a.email}</b><p className="break-all text-sm">{a.email}</p><code className="break-all text-xs">{a.admin_user_id}</code><p className="text-xs text-[var(--color-muted-foreground)]">{t('data_granted')} {formatAdminDate(a.granted_at,locale)} · {t('data_last_session')} {formatAdminDate(a.last_session_at,locale)}</p></div><AdminStatus value={a.grant_status}/></li>)}</ul>}<AdminPagination hasMore={more} cursor={cursor} busy={busy} locale={locale} onNext={()=>cursor&&void load(cursor)}/></AdminCard>}</AdminPage>
}
