'use client';

import { useLocale, useTranslations } from 'next-intl';
import { useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import { ConfirmDialog } from '@/components/ui/confirm-dialog';
import { DeliveryImage } from '@/features/gallery/components/delivery-image';
import { getApiV1AdminAlbumsAlbumIdOperationalHold, postApiV1AdminAlbumsAlbumIdOperationalHold, deleteApiV1AdminAlbumsAlbumIdOperationalHold } from '@/lib/api/generated/admin-hold/admin-hold';
import { getApiV1AdminAlbumsAlbumIdSensitiveMedia } from '@/lib/api/generated/admin-sensitive-access/admin-sensitive-access';
import { postApiV1AdminAlbumsAlbumIdSensitiveAccessGrants, deleteApiV1AdminSensitiveAccessGrantsGrantId } from '@/lib/api/generated/admin-sensitive/admin-sensitive';
import { postApiV1AdminAuthStepUp } from '@/lib/api/generated/admin-auth/admin-auth';
import type { OperationalHoldState, SensitiveAccessGrant, AdminSensitiveMedia } from '@/lib/api/generated/index.schemas';
import { AdminCard, AdminEmpty, AdminError, AdminFeedback, AdminField, AdminPage, AdminStatus, adminCsrfHeaders, adminInputClass, formatAdminDate, type AdminLocale, useAdminOnline } from './common';

function useLocaleCopy() { const locale = (useLocale() === 'en' ? 'en' : 'id') as AdminLocale; const t = useTranslations('admin.legacyCopy'); return { locale, id: locale === 'id', t }; }

export function AdminSensitiveAccess({ albumId }: { albumId: string }) {
  const { locale, t } = useLocaleCopy(); const online = useAdminOnline();
  const [reason, setReason] = useState(''); const [totp, setTotp] = useState(''); const [grant, setGrant] = useState<SensitiveAccessGrant | null>(null); const [rows, setRows] = useState<AdminSensitiveMedia[]>([]); const [cursor, setCursor] = useState(''); const [error, setError] = useState<number>(); const [busy, setBusy] = useState(false); const [confirm, setConfirm] = useState(false);
  useEffect(() => {
    if (!grant) return;
    const remaining = Math.max(0, Date.parse(grant.expires_at) - Date.now());
    const timer = window.setTimeout(() => { setGrant(null); setRows([]); setCursor(''); }, remaining);
    return () => window.clearTimeout(timer);
  }, [grant]);
  async function showMedia(current: SensitiveAccessGrant, next?: string) { setError(undefined); try { const r = await getApiV1AdminAlbumsAlbumIdSensitiveMedia(albumId, { grant_id: current.grant_id, limit: 20, ...(next ? { cursor: next } : {}) }); if (r.status === 200) { setRows(r.data.data); setCursor(r.data.meta.next_cursor ?? ''); } else { setError(r.status); if (r.status === 401 || r.status === 403 || r.status === 410) { setGrant(null); setRows([]); } } } catch { setError(0); } }
  async function begin() { if (!online || busy || !reason.trim() || !totp) return; setBusy(true); setError(undefined); try { const step = await postApiV1AdminAuthStepUp({ totp_code: totp }, { headers: await adminCsrfHeaders() }); setTotp(''); if (step.status !== 200) { setError(step.status); return; } const created = await postApiV1AdminAlbumsAlbumIdSensitiveAccessGrants(albumId, { reason: reason.trim() }, { headers: await adminCsrfHeaders() }); if (created.status === 201) { setGrant(created.data.data); setReason(''); await showMedia(created.data.data); } else setError(created.status); } catch { setTotp(''); setError(0); } finally { setBusy(false); setConfirm(false); } }
  async function revoke() { if (!grant) return; setBusy(true); try { const r = await deleteApiV1AdminSensitiveAccessGrantsGrantId(grant.grant_id, { headers: await adminCsrfHeaders() }); if (r.status === 200) { setGrant(null); setRows([]); setCursor(''); } else setError(r.status); } catch { setError(0); } finally { setBusy(false); setConfirm(false); } }
  return <AdminPage title={t('privileged_sensitive_media_access')} description={t('privileged_temporary_album_scoped_view_only_a')}>
    <AdminCard title={t('privileged_access_boundaries')}><p className="text-sm leading-6">{t('privileged_no_download_sharing_zip_moderation')}</p></AdminCard>
    {!grant ? <AdminCard title={t('privileged_request_temporary_grant')}><div className="grid gap-4 sm:grid-cols-2"><AdminField label={t('privileged_audit_reason')}><textarea className={adminInputClass} rows={3} maxLength={500} required value={reason} onChange={e => setReason(e.target.value)} /></AdminField><AdminField label={t('privileged_totp_code')}><input className={adminInputClass} type="text" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6,12}" maxLength={12} value={totp} onChange={e => setTotp(e.target.value.replace(/\D/g, '').slice(0,12))} /></AdminField></div><Button className="mt-4" disabled={!online || busy || !reason.trim() || totp.length < 6} loading={busy} onClick={() => setConfirm(true)}>{t('privileged_continue_to_confirmation')}</Button></AdminCard> : <>
      <AdminCard title={t('privileged_active_grant')}><div className="flex flex-wrap items-start justify-between gap-3"><dl className="min-w-0 text-sm"><dt>{t('privileged_grant_id')}</dt><dd className="break-all font-mono">{grant.grant_id}</dd><dt className="mt-3">{t('privileged_expires')}</dt><dd>{formatAdminDate(grant.expires_at, locale)}</dd><dt className="mt-3">{t('privileged_scope')}</dt><dd>{t('privileged_this_album_view_only')}</dd></dl><Button variant="danger" disabled={!online || busy} onClick={() => setConfirm(true)}>{t('privileged_revoke_access_and_close_workspace')}</Button></div></AdminCard>
      <AdminCard title={t('privileged_authorized_media')}>{error !== undefined && <AdminFeedback>{error === 410 || error === 403 ? (t('privileged_the_grant_expired_or_access_was_re')) : (t('privileged_media_could_not_be_loaded_try_relo'))}</AdminFeedback>}{rows.length === 0 ? <AdminEmpty>{t('privileged_no_media_in_this_page')}</AdminEmpty> : <ul className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{rows.map(photo => <li key={photo.photo_id} className="overflow-hidden rounded-[var(--radius-md)] border border-[var(--color-border)]"><DeliveryImage src={photo.media.url} alt={t('privileged_private_photo_under_sensitive_acce')} unavailableLabel={t('privileged_media_is_no_longer_available')} className="aspect-square w-full object-cover" /><p className="break-all p-3 text-xs text-[var(--color-muted-foreground)]">{photo.photo_id}<br />{formatAdminDate(photo.created_at, locale)}</p></li>)}</ul>}{cursor && <Button variant="secondary" disabled={busy} className="mt-4" onClick={() => grant && void showMedia(grant,cursor)}>{t('privileged_load_next_page')}</Button>}</AdminCard>
    </>}
    {error !== undefined && error !== 410 && error !== 403 && <AdminError locale={locale} status={error} retry={() => grant && void showMedia(grant)} />}
    <ConfirmDialog open={confirm} title={grant ? (t('privileged_revoke_media_grant')) : (t('privileged_create_temporary_grant'))} description={grant ? (t('privileged_media_access_and_currently_display')) : (t('privileged_the_grant_is_temporary_limited_to'))} confirmLabel={t('privileged_confirm')} cancelLabel={t('privileged_cancel')} destructive onCancel={() => setConfirm(false)} onConfirm={() => grant ? void revoke() : void begin()} disabled={busy || !online} />
  </AdminPage>;
}

export function AdminOperationalHold({ albumId }: { albumId: string }) {
  const { locale, t } = useLocaleCopy(); const online = useAdminOnline();
  const [state, setState] = useState<OperationalHoldState | null>(null); const [reason, setReason] = useState(''); const [totp, setTotp] = useState(''); const [busy, setBusy] = useState(true); const [mutating, setMutating] = useState(false); const [error, setError] = useState<number>(); const [confirm, setConfirm] = useState(false);
  async function load() { setBusy(true); setError(undefined); try { const r = await getApiV1AdminAlbumsAlbumIdOperationalHold(albumId); if (r.status === 200) setState(r.data.data); else setError(r.status); } catch { setError(0); } finally { setBusy(false); } }
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps -- load current server hold state after mount
  useEffect(() => { void load(); }, [albumId]);
  async function mutate() { if (!online || mutating || !reason.trim() || !totp) return; setMutating(true); setError(undefined); try { const step = await postApiV1AdminAuthStepUp({ totp_code: totp }, { headers: await adminCsrfHeaders() }); setTotp(''); if (step.status !== 200) { setError(step.status); return; } const headers = await adminCsrfHeaders(); const r = state?.active_hold ? await deleteApiV1AdminAlbumsAlbumIdOperationalHold(albumId, { reason: reason.trim() }, { headers }) : await postApiV1AdminAlbumsAlbumIdOperationalHold(albumId, { reason: reason.trim() }, { headers }); if (r.status === 200) { setReason(''); await load(); } else setError(r.status); } catch { setTotp(''); setError(0); } finally { setMutating(false); setConfirm(false); } }
  return <AdminPage title={'Operational Hold'} description={t('privileged_this_containment_closes_guest_acce')}>
    <AdminCard title={t('privileged_current_state')}>{busy ? <p role="status">{t('privileged_loading_state')}</p> : error !== undefined ? <AdminError locale={locale} status={error} retry={() => void load()} /> : <><AdminStatus value={state?.active_hold ? 'ACTIVE HOLD' : 'NO ACTIVE HOLD'} />{state?.active_hold && <dl className="mt-4 space-y-2 text-sm"><div><dt>{t('privileged_started')}</dt><dd>{formatAdminDate(state.active_hold.created_at, locale)}</dd></div><div><dt>{t('privileged_reason')}</dt><dd className="break-words">{state.active_hold.reason}</dd></div></dl>}</>}</AdminCard>
    <AdminCard title={state?.active_hold ? (t('privileged_release_hold')) : (t('privileged_create_hold'))}><p className="mb-4 text-sm leading-6 text-[var(--color-muted-foreground)]">{t('privileged_this_action_requires_an_audit_reas')}</p><div className="grid gap-4 sm:grid-cols-2"><AdminField label={t('privileged_required_reason')}><textarea className={adminInputClass} rows={3} maxLength={500} value={reason} onChange={e => setReason(e.target.value)} /></AdminField><AdminField label={t('privileged_totp_code')}><input className={adminInputClass} type="text" inputMode="numeric" autoComplete="one-time-code" maxLength={12} value={totp} onChange={e => setTotp(e.target.value.replace(/\D/g,'').slice(0,12))} /></AdminField></div><Button className="mt-4" variant={state?.active_hold ? 'secondary' : 'danger'} disabled={!online || busy || mutating || !reason.trim() || totp.length < 6} loading={mutating} onClick={() => setConfirm(true)}>{state?.active_hold ? (t('privileged_confirm_release')) : (t('privileged_confirm_operational_hold'))}</Button></AdminCard>
    {error !== undefined && !busy && <AdminError locale={locale} status={error} retry={() => void load()} />}
    <ConfirmDialog open={confirm} title={state?.active_hold ? (t('privileged_release_operational_hold')) : (t('privileged_activate_operational_hold'))} description={state?.active_hold ? (t('privileged_the_server_will_continue_to_apply')) : (t('privileged_guest_access_and_the_online_featur'))} confirmLabel={t('privileged_continue')} cancelLabel={t('privileged_cancel')} destructive onCancel={() => setConfirm(false)} onConfirm={() => void mutate()} disabled={!online || mutating} />
  </AdminPage>;
}
