'use client';

import { useLocale } from 'next-intl';
import { useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import { ConfirmDialog } from '@/components/ui/confirm-dialog';
import { DeliveryImage } from '@/features/gallery/components/delivery-image';
import { getApiV1AdminAlbumsAlbumIdOperationalHold, postApiV1AdminAlbumsAlbumIdOperationalHold, deleteApiV1AdminAlbumsAlbumIdOperationalHold } from '@/lib/api/generated/admin-hold/admin-hold';
import { getApiV1AdminAlbumsAlbumIdSensitiveMedia } from '@/lib/api/generated/admin-sensitive-access/admin-sensitive-access';
import { postApiV1AdminAlbumsAlbumIdSensitiveAccessGrants, deleteApiV1AdminSensitiveAccessGrantsGrantId } from '@/lib/api/generated/admin-sensitive/admin-sensitive';
import { postApiV1AdminAuthStepUp } from '@/lib/api/generated/admin-auth/admin-auth';
import type { OperationalHoldState, SensitiveAccessGrant, AdminSensitiveMedia } from '@/lib/api/generated/index.schemas';
import { AdminCard, AdminEmpty, AdminError, AdminFeedback, AdminField, AdminPage, AdminStatus, adminCsrfHeaders, adminInputClass, formatAdminDate, type AdminLocale, useAdminOnline } from './common';

function useLocaleCopy() { const locale = (useLocale() === 'en' ? 'en' : 'id') as AdminLocale; return { locale, id: locale === 'id' }; }

export function AdminSensitiveAccess({ albumId }: { albumId: string }) {
  const { locale, id } = useLocaleCopy(); const online = useAdminOnline();
  const [reason, setReason] = useState(''); const [totp, setTotp] = useState(''); const [grant, setGrant] = useState<SensitiveAccessGrant | null>(null); const [rows, setRows] = useState<AdminSensitiveMedia[]>([]); const [cursor, setCursor] = useState(''); const [error, setError] = useState<number>(); const [busy, setBusy] = useState(false); const [confirm, setConfirm] = useState(false);
  useEffect(() => {
    if (!grant) return;
    const remaining = Math.max(0, Date.parse(grant.expires_at) - Date.now());
    const timer = window.setTimeout(() => { setGrant(null); setRows([]); setCursor(''); }, remaining);
    return () => window.clearTimeout(timer);
  }, [grant]);
  async function showMedia(current: SensitiveAccessGrant, next?: string) { setError(undefined); try { const r = await getApiV1AdminAlbumsAlbumIdSensitiveMedia(albumId, { grant_id: current.grant_id, limit: 20, ...(next ? { cursor: next } : {}) }); if (r.status === 200) { setRows(r.data.data); setCursor(r.data.meta.next_cursor ?? ''); } else { setError(r.status); if (r.status === 401 || r.status === 403 || r.status === 410) { setGrant(null); setRows([]); } } } catch { setError(0); } }
  async function begin() { if (!online || busy || !reason.trim() || !totp) return; setBusy(true); setError(undefined); try { const step = await postApiV1AdminAuthStepUp({ totp_code: totp }, { headers: await adminCsrfHeaders() }); setTotp(''); if (step.status !== 200) { setError(step.status); return; } const created = await postApiV1AdminAlbumsAlbumIdSensitiveAccessGrants(albumId, { reason: reason.trim() }, { headers: await adminCsrfHeaders() }); if (created.status === 201) { setGrant(created.data.data); setReason(''); await showMedia(created.data.data); } else setError(created.status); } catch { setTotp(''); setError(0); } finally { setBusy(false); setConfirm(false); } }
  async function revoke() { if (!grant) return; setBusy(true); try { const r = await deleteApiV1AdminSensitiveAccessGrantsGrantId(grant.grant_id, { headers: await adminCsrfHeaders() }); if (r.status === 200) { setGrant(null); setRows([]); setCursor(''); } else setError(r.status); } catch { setError(0); } finally { setBusy(false); setConfirm(false); } }
  return <AdminPage title={id ? 'Akses media sensitif' : 'Sensitive media access'} description={id ? 'Akses sementara, terbatas pada album ini, hanya untuk melihat, dan dicatat. Operational Hold tidak memberikan akses media.' : 'Temporary, album-scoped, view-only access that is audited. Operational Hold does not grant media access.'}>
    <AdminCard title={id ? 'Batas akses' : 'Access boundaries'}><p className="text-sm leading-6">{id ? 'Tidak ada unduhan, berbagi, ZIP, moderasi, hapus, atau pemulihan. Otorisasi media diperiksa server pada setiap pengiriman.' : 'No download, sharing, ZIP, moderation, delete, or restore. The server checks media authorization on every delivery.'}</p></AdminCard>
    {!grant ? <AdminCard title={id ? 'Minta grant sementara' : 'Request temporary grant'}><div className="grid gap-4 sm:grid-cols-2"><AdminField label={id ? 'Alasan audit' : 'Audit reason'}><textarea className={adminInputClass} rows={3} maxLength={500} required value={reason} onChange={e => setReason(e.target.value)} /></AdminField><AdminField label={id ? 'Kode TOTP' : 'TOTP code'}><input className={adminInputClass} type="text" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6,12}" maxLength={12} value={totp} onChange={e => setTotp(e.target.value.replace(/\D/g, '').slice(0,12))} /></AdminField></div><Button className="mt-4" disabled={!online || busy || !reason.trim() || totp.length < 6} loading={busy} onClick={() => setConfirm(true)}>{id ? 'Lanjutkan setelah konfirmasi' : 'Continue to confirmation'}</Button></AdminCard> : <>
      <AdminCard title={id ? 'Grant aktif' : 'Active grant'}><div className="flex flex-wrap items-start justify-between gap-3"><dl className="min-w-0 text-sm"><dt>{id ? 'ID grant' : 'Grant ID'}</dt><dd className="break-all font-mono">{grant.grant_id}</dd><dt className="mt-3">{id ? 'Berakhir' : 'Expires'}</dt><dd>{formatAdminDate(grant.expires_at, locale)}</dd><dt className="mt-3">{id ? 'Cakupan' : 'Scope'}</dt><dd>{id ? 'Album ini · hanya lihat' : 'This album · view only'}</dd></dl><Button variant="danger" disabled={!online || busy} onClick={() => setConfirm(true)}>{id ? 'Cabut akses dan tutup workspace' : 'Revoke access and close workspace'}</Button></div></AdminCard>
      <AdminCard title={id ? 'Media yang diizinkan' : 'Authorized media'}>{error !== undefined && <AdminFeedback>{error === 410 || error === 403 ? (id ? 'Grant berakhir atau akses dicabut. Workspace ditutup.' : 'The grant expired or access was revoked. The workspace is closed.') : (id ? 'Media tidak dapat dimuat. Coba muat ulang.' : 'Media could not be loaded. Try reloading.')}</AdminFeedback>}{rows.length === 0 ? <AdminEmpty>{id ? 'Tidak ada media dalam halaman ini.' : 'No media in this page.'}</AdminEmpty> : <ul className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{rows.map(photo => <li key={photo.photo_id} className="overflow-hidden rounded-[var(--radius-md)] border border-[var(--color-border)]"><DeliveryImage src={photo.media.url} alt={id ? 'Foto privat dalam akses sensitif' : 'Private photo under sensitive access'} unavailableLabel={id ? 'Media tidak lagi tersedia' : 'Media is no longer available'} className="aspect-square w-full object-cover" /><p className="break-all p-3 text-xs text-[var(--color-muted-foreground)]">{photo.photo_id}<br />{formatAdminDate(photo.created_at, locale)}</p></li>)}</ul>}{cursor && <Button variant="secondary" disabled={busy} className="mt-4" onClick={() => grant && void showMedia(grant,cursor)}>{id ? 'Muat berikutnya' : 'Load next page'}</Button>}</AdminCard>
    </>}
    {error !== undefined && error !== 410 && error !== 403 && <AdminError locale={locale} status={error} retry={() => grant && void showMedia(grant)} />}
    <ConfirmDialog open={confirm} title={grant ? (id ? 'Cabut grant media?' : 'Revoke media grant?') : (id ? 'Buat grant sementara?' : 'Create temporary grant?')} description={grant ? (id ? 'Akses media dan gambar yang sedang ditampilkan akan segera ditutup.' : 'Media access and currently displayed images will be closed immediately.') : (id ? 'Grant hanya untuk album ini, bersifat sementara, hanya lihat, dan semua akses akan diaudit.' : 'The grant is temporary, limited to this album, view-only, and all access is audited.')} confirmLabel={id ? 'Konfirmasi' : 'Confirm'} cancelLabel={id ? 'Batal' : 'Cancel'} destructive onCancel={() => setConfirm(false)} onConfirm={() => grant ? void revoke() : void begin()} disabled={busy || !online} />
  </AdminPage>;
}

export function AdminOperationalHold({ albumId }: { albumId: string }) {
  const { locale, id } = useLocaleCopy(); const online = useAdminOnline();
  const [state, setState] = useState<OperationalHoldState | null>(null); const [reason, setReason] = useState(''); const [totp, setTotp] = useState(''); const [busy, setBusy] = useState(true); const [mutating, setMutating] = useState(false); const [error, setError] = useState<number>(); const [confirm, setConfirm] = useState(false);
  async function load() { setBusy(true); setError(undefined); try { const r = await getApiV1AdminAlbumsAlbumIdOperationalHold(albumId); if (r.status === 200) setState(r.data.data); else setError(r.status); } catch { setError(0); } finally { setBusy(false); } }
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps -- load current server hold state after mount
  useEffect(() => { void load(); }, [albumId]);
  async function mutate() { if (!online || mutating || !reason.trim() || !totp) return; setMutating(true); setError(undefined); try { const step = await postApiV1AdminAuthStepUp({ totp_code: totp }, { headers: await adminCsrfHeaders() }); setTotp(''); if (step.status !== 200) { setError(step.status); return; } const headers = await adminCsrfHeaders(); const r = state?.active_hold ? await deleteApiV1AdminAlbumsAlbumIdOperationalHold(albumId, { reason: reason.trim() }, { headers }) : await postApiV1AdminAlbumsAlbumIdOperationalHold(albumId, { reason: reason.trim() }, { headers }); if (r.status === 200) { setReason(''); await load(); } else setError(r.status); } catch { setTotp(''); setError(0); } finally { setMutating(false); setConfirm(false); } }
  return <AdminPage title={id ? 'Operational Hold' : 'Operational Hold'} description={id ? 'Penahanan ini menghentikan akses tamu, kamera, galeri, berbagi, unduhan, dan pembuatan ZIP baru. Tidak mengubah jadwal, pembayaran, kepemilikan, retensi, atau media.' : 'This containment closes guest access, camera, gallery, sharing, downloads, and new ZIP creation. It does not change schedule, payment, ownership, retention, or media.'}>
    <AdminCard title={id ? 'Status saat ini' : 'Current state'}>{busy ? <p role="status">{id ? 'Memuat status…' : 'Loading state…'}</p> : error !== undefined ? <AdminError locale={locale} status={error} retry={() => void load()} /> : <><AdminStatus value={state?.active_hold ? 'ACTIVE HOLD' : 'NO ACTIVE HOLD'} />{state?.active_hold && <dl className="mt-4 space-y-2 text-sm"><div><dt>{id ? 'Dimulai' : 'Started'}</dt><dd>{formatAdminDate(state.active_hold.created_at, locale)}</dd></div><div><dt>{id ? 'Alasan' : 'Reason'}</dt><dd className="break-words">{state.active_hold.reason}</dd></div></dl>}</>}</AdminCard>
    <AdminCard title={state?.active_hold ? (id ? 'Lepaskan penahanan' : 'Release hold') : (id ? 'Buat penahanan' : 'Create hold')}><p className="mb-4 text-sm leading-6 text-[var(--color-muted-foreground)]">{id ? 'Aksi memerlukan alasan audit dan MFA step-up. Hold tidak memberikan hak untuk melihat foto privat; akses media sensitif tetap memiliki grant dan alurnya sendiri.' : 'This action requires an audit reason and MFA step-up. A hold does not grant private-photo access; Sensitive Access has its own independent grant and flow.'}</p><div className="grid gap-4 sm:grid-cols-2"><AdminField label={id ? 'Alasan wajib' : 'Required reason'}><textarea className={adminInputClass} rows={3} maxLength={500} value={reason} onChange={e => setReason(e.target.value)} /></AdminField><AdminField label={id ? 'Kode TOTP' : 'TOTP code'}><input className={adminInputClass} type="text" inputMode="numeric" autoComplete="one-time-code" maxLength={12} value={totp} onChange={e => setTotp(e.target.value.replace(/\D/g,'').slice(0,12))} /></AdminField></div><Button className="mt-4" variant={state?.active_hold ? 'secondary' : 'danger'} disabled={!online || busy || mutating || !reason.trim() || totp.length < 6} loading={mutating} onClick={() => setConfirm(true)}>{state?.active_hold ? (id ? 'Konfirmasi pelepasan' : 'Confirm release') : (id ? 'Konfirmasi Operational Hold' : 'Confirm Operational Hold')}</Button></AdminCard>
    {error !== undefined && !busy && <AdminError locale={locale} status={error} retry={() => void load()} />}
    <ConfirmDialog open={confirm} title={state?.active_hold ? (id ? 'Lepaskan Operational Hold?' : 'Release Operational Hold?') : (id ? 'Aktifkan Operational Hold?' : 'Activate Operational Hold?')} description={state?.active_hold ? (id ? 'Server akan tetap menerapkan jadwal dan aturan siklus hidup saat ini. Pelepasan tidak menjamin kamera dibuka kembali.' : 'The server will continue to apply the current schedule and lifecycle rules. Releasing the hold does not guarantee capture will reopen.') : (id ? 'Akses tamu dan fitur online yang disebut di atas akan ditahan. Data album tidak dihapus.' : 'Guest access and the online features listed above will be contained. Album data is not deleted.')} confirmLabel={id ? 'Lanjutkan' : 'Continue'} cancelLabel={id ? 'Batal' : 'Cancel'} destructive onCancel={() => setConfirm(false)} onConfirm={() => void mutate()} disabled={!online || mutating} />
  </AdminPage>;
}
