export type Locale = 'id' | 'en';

export type PriceOption = {
  label: string;
  photos: number;
  price: number;
  displayCount: string;
};

export const priceOptions: PriceOption[] = [
  { label: '30', photos: 30, price: 0, displayCount: '30' },
  { label: '100', photos: 100, price: 100_000, displayCount: '100' },
  { label: '250', photos: 250, price: 230_000, displayCount: '250' },
  { label: '500', photos: 500, price: 450_000, displayCount: '500' },
  { label: '700', photos: 700, price: 620_000, displayCount: '700' },
  { label: '1K', photos: 1_000, price: 840_000, displayCount: '1.000' },
  { label: '10K', photos: 10_000, price: 1_100_000, displayCount: '10.000' },
];

export const content = {
  id: {
    nav: {
      how: 'Cara Kerja',
      pricing: 'Harga',
      faq: 'FAQ',
      signIn: 'Masuk',
      createAlbum: 'Buat Album Gratis',
      openMenu: 'Buka menu navigasi',
      closeMenu: 'Tutup menu navigasi',
      switchToLight: 'Ganti ke tema terang',
      switchToDark: 'Ganti ke tema gelap',
      language: 'Bahasa',
      indonesian: 'Bahasa Indonesia',
      english: 'Bahasa Inggris',
    },
    hero: {
      eyebrow: 'DOKUMENTASI PARTISIPATIF UNTUK BERBAGAI ACARA',
      title: 'Satu momen. Banyak sudut.',
      description: 'Jangan sampai momen dari sudut lain terlewat. Bisa jadi, justru di sanalah bagian paling istimewa tersimpan. Bagikan satu QR dan biarkan orang-orang di acara ikut motret langsung dari HP.',
      proof: ['Foto terkumpul dalam satu album', 'Tanpa install aplikasi & tanpa akun peserta'],
      secondary: 'Lihat Cara Kerjanya',
      microcopy: 'Mulai Gratis',
      visualLabel: 'Momen dari berbagai sudut',
      visualHint: 'Scan QR. Motret langsung dari HP.',
    },
    how: {
      eyebrow: 'CARA KERJA',
      title: 'Dari QR ke album dalam 3 langkah.',
      description: 'Kamu siapkan albumnya. Peserta tinggal scan & motret, lalu momen dari berbagai sudut mulai terkumpul.',
      steps: [
        { title: 'Buat album', description: 'Siapkan album untuk acaramu dan atur kebutuhan dokumentasinya.' },
        { title: 'Bagikan QR', description: 'Tampilkan QR di lokasi acara atau bagikan link kepada orang-orang yang ikut.' },
        { title: 'Momen terkumpul', description: 'Mereka scan QR, motret langsung dari HP, lalu fotonya masuk ke album yang sama.' },
      ],
      cta: 'Lihat Cara Kerja Lengkap',
    },
    benefits: {
      eyebrow: 'KENAPA KEPOTRET',
      title: 'Lebih banyak sudut. Lebih sedikit repot.',
      description: 'Dokumentasi acara jadi lebih hidup ketika lebih banyak orang ikut menangkap momennya. Kepotret membantu semuanya terkumpul tanpa bikin prosesnya jadi ribet.',
      items: [
        { title: 'Capture momen dari lebih banyak sudut', description: 'Setiap orang melihat hal yang berbeda. Kumpulkan berbagai perspektif itu dalam satu album.' },
        { title: 'Nggak perlu minta foto satu-satu', description: 'Foto yang berhasil dikirim langsung terkumpul di album acara, jadi kamu tidak perlu mengejar kiriman satu per satu.' },
        { title: 'Mudah untuk ikut', description: 'Peserta cukup scan QR dan motret langsung dari HP, tanpa perlu install aplikasi atau membuat akun.' },
        { title: 'Kendali tetap di kamu', description: 'Atur kapan peserta bisa motret, kapan galeri dibuka, serta kelola foto dan akses album sesuai kebutuhan acara.' },
        { title: 'Lebih fleksibel untuk acara ramai', description: 'Jumlah peserta tidak dibatasi paket. Pilih kapasitas foto sesuai kebutuhan, jadi kamu tidak perlu menyesuaikan paket hanya karena jumlah orang yang ikut bertambah.' },
      ],
    },
    differentiation: {
      eyebrow: 'KENAPA KEPOTRET',
      title: 'Ajak lebih banyak orang ikut menangkap momen.',
      description: 'Jumlah peserta tidak menentukan paket Kepotret. Kamu cukup memilih kapasitas foto sesuai kebutuhan acara, lalu ajak sebanyak mungkin orang untuk ikut menangkap momennya.',
      items: [
        { title: 'Unduh banyak foto sekaligus', description: 'Butuh semua hasil dokumentasi? Host bisa menyiapkan dan mengunduh album dalam bentuk ZIP agar lebih praktis.' },
        { title: 'Kendalikan foto yang tampil', description: 'Host dapat mengatur moderasi, menyembunyikan foto, dan mengelola foto yang ditampilkan kepada peserta.' },
        { title: 'Ajak WO/EO bantu kelola album', description: 'Bagikan pekerjaan setup, moderasi, atau ekspor kepada WO/EO dengan izin yang kamu tentukan, supaya kamu bisa lebih fokus menikmati rangkaian acara.' },
        { title: 'Bagikan lewat WhatsApp dengan mudah', description: 'Setelah foto dapat dilihat, bagikan link foto melalui WhatsApp atau salin link untuk dikirim ke siapa pun.' },
      ],
    },
    useCases: {
      eyebrow: 'UNTUK BERBAGAI ACARA',
      title: 'Setiap acara punya momen dari sudut yang berbeda.',
      description: 'Dari acara pribadi sampai kegiatan besar, Kepotret membantu mengumpulkan perspektif orang-orang yang ikut hadir dalam satu album.',
      items: [
        { title: 'Wedding & Celebration', description: 'Tangkap bukan hanya momen utama, tapi juga ekspresi keluarga, teman, dan suasana yang mungkin tidak terlihat dari satu kamera saja.' },
        { title: 'Birthday & Personal Event', description: 'Kumpulkan momen spontan dari orang-orang terdekat tanpa harus meminta kiriman foto satu per satu.' },
        { title: 'Community & Gathering', description: 'Biar anggota dan peserta ikut mendokumentasikan kegiatan dari sudut mereka masing-masing.' },
        { title: 'Sport & Competition', description: 'Abadikan aksi, supporter, suasana venue, hingga momen setelah pertandingan dari lebih banyak perspektif.' },
        { title: 'Corporate & Organization', description: 'Lengkapi dokumentasi town hall, gathering, offsite, atau aktivitas tim dengan kontribusi dari lebih banyak peserta.' },
        { title: 'Trip & Travel', description: 'Satu perjalanan, banyak cerita. Kumpulkan momen dari teman seperjalanan tanpa foto tercecer di banyak HP.' },
      ],
    },
    guest: {
      eyebrow: 'PENGALAMAN PESERTA',
      title: 'Untuk peserta, sesederhana scan lalu motret.',
      description: 'Peserta tidak perlu install aplikasi atau membuat akun. Cukup scan QR, isi nama, izinkan kamera, lalu mulai motret langsung dari HP.',
      steps: [
        { title: 'Scan QR', description: 'Buka QR atau link acara langsung dari HP.' },
        { title: 'Isi nama', description: 'Masukkan nama yang akan tampil sebagai label pada foto.' },
        { title: 'Izinkan kamera', description: 'Beri akses kamera agar bisa mulai memotret.' },
        { title: 'Motret & gunakan foto', description: 'Ambil foto, lihat hasilnya, lalu pilih gunakan foto atau ambil ulang.' },
      ],
      badges: ['Tanpa install aplikasi', 'Tanpa akun peserta'],
      cta: 'Lihat Cara Kerja Lengkap',
    },
    pricing: {
      eyebrow: 'HARGA',
      title: 'Pilih kapasitas sesuai kebutuhan acaramu.',
      description: 'Mulai gratis dengan 30 foto. Butuh lebih banyak? Geser kapasitas dan pilih jumlah foto yang paling cocok untuk acaramu - jumlah peserta tetap tidak dibatasi paket.',
      prompt: 'Berapa banyak momen yang ingin kamu tampung?',
      photoUnit: 'foto',
      free: 'Gratis',
      proof: ['Jumlah peserta tidak dibatasi paket.', 'Untuk satu album.'],
      freeCta: 'Buat Album Gratis',
      paidCta: 'Pilih {capacity} Foto',
    },
    trust: {
      eyebrow: 'KENDALI & KEAMANAN',
      title: 'Momen bersama, tetap dalam kendalimu.',
      description: 'Kepotret dirancang agar partisipasi tetap mudah tanpa menghilangkan kendali Host atas album, akses, dan foto yang ditampilkan.',
      items: [
        { title: 'Atur siapa yang bisa melihat', description: 'Gunakan akses album sesuai kebutuhan, termasuk pilihan PIN bila diperlukan.' },
        { title: 'Kendalikan foto yang tampil', description: 'Host dapat mengatur moderasi, menyembunyikan foto, dan mengelola galeri sebelum foto ditampilkan kepada peserta.' },
        { title: 'Masa akses yang jelas', description: 'Album memiliki periode akses yang terjadwal, lengkap dengan pengingat sebelum masa akses berakhir.' },
      ],
      cta: 'Pelajari Keamanan',
    },
    faq: {
      eyebrow: 'FAQ',
      title: 'Masih ada yang ingin kamu pastikan?',
      description: 'Ini beberapa hal yang paling sering perlu diketahui sebelum membuat album Kepotret.',
      items: [
        { question: 'Apakah peserta harus install aplikasi?', answer: 'Tidak. Peserta cukup scan QR atau membuka link acara, lalu motret langsung dari HP melalui browser.' },
        { question: 'Apakah peserta harus membuat akun?', answer: 'Tidak. Peserta hanya perlu mengisi nama untuk mulai bergabung dan memotret. Nama tersebut akan digunakan sebagai label pada foto.' },
        { question: 'Berapa banyak peserta yang bisa ikut?', answer: 'Jumlah peserta tidak dibatasi paket. Yang kamu pilih adalah kapasitas foto untuk album.' },
        { question: 'Apakah peserta bisa mengambil foto dari galeri HP?', answer: 'Tidak. Foto album Kepotret diambil langsung melalui kamera selama waktu memotret masih aktif.' },
        { question: 'Kapan foto bisa dilihat peserta?', answer: 'Host memilih kapan galeri dibuka: D+1, D+3, D+5, atau D+7 setelah acara selesai. Foto yang belum diizinkan tampil tetap tidak terlihat oleh peserta.' },
        { question: 'Berapa lama album bisa diakses?', answer: 'Akses normal album berlangsung hingga 30 hari setelah acara selesai. Setelah itu tersedia masa pemulihan terbatas selama 7 hari khusus untuk pemilik album sebelum media utama dihapus.' },
        { question: 'Kalau kapasitas foto hampir habis, apakah bisa ditambah?', answer: 'Bisa, selama periode upgrade masih tersedia. Pembelian atau upgrade ditutup 120 menit sebelum waktu acara berakhir.' },
        { question: 'Apakah album bisa dibuat lebih privat?', answer: 'Bisa. Album menggunakan akses berbasis link dan Host dapat menambahkan PIN opsional, mengatur siapa yang dapat melihat galeri, serta mengelola foto yang ditampilkan.' },
      ],
      allQuestions: 'Lihat semua pertanyaan',
    },
    final: {
      title: 'Acara berikutnya, lihat dari lebih banyak sudut.',
      description: 'Buat album Kepotret, bagikan QR, dan biarkan momen dari berbagai perspektif mulai terkumpul.',
      microcopy: 'Mulai Gratis',
    },
    footer: {
      brandLine: 'Satu momen. Banyak sudut.',
      descriptor: 'Dokumentasi partisipatif untuk berbagai acara.',
      product: 'Produk',
      help: 'Bantuan',
      legal: 'Legal',
      social: 'Ikuti Kami',
      helpCenter: 'Pusat Bantuan',
      security: 'Keamanan',
      contact: 'Hubungi Kami',
      privacy: 'Kebijakan Privasi',
      terms: 'Syarat & Ketentuan',
      unavailable: 'Belum tersedia',
      copyright: '© 2026 Kepotret. All rights reserved.',
      socialLabels: ['Instagram', 'TikTok', 'WhatsApp'],
    },
    publicPages: {
      howTitle: 'Cara Kerja Kepotret',
      howDescription: 'Kamu siapkan album, bagikan QR, lalu momen dari berbagai sudut terkumpul dalam satu album.',
      priceTitle: 'Harga',
      faqTitle: 'Pertanyaan yang sering diajukan',
      helpTitle: 'Pusat Bantuan',
      helpDescription: 'Untuk informasi bantuan dan kontak, gunakan kanal resmi Kepotret yang tersedia.',
      contactTitle: 'Hubungi Kami',
      unavailable: 'Informasi ini belum tersedia.',
      privacyTitle: 'Kebijakan Privasi',
      termsTitle: 'Syarat & Ketentuan',
      legalUnavailable: 'Dokumen resmi belum tersedia.',
      securityTitle: 'Keamanan & Privasi',
      securityDescription: 'Kepotret dirancang agar partisipasi tetap mudah tanpa menghilangkan kendali Host atas album, akses, dan foto yang ditampilkan.',
    },
    auth: {
      signInTitle: 'Masuk ke Kepotret',
      signInDescription: 'Gunakan akun Google untuk masuk sebagai Host atau melanjutkan undangan kolaborasi.',
      google: 'Lanjutkan dengan Google',
      processingTitle: 'Menghubungkan ke Google',
      processingDescription: 'Kami sedang menyiapkan proses masuk yang aman. Kamu akan diarahkan ke Google.',
      failedTitle: 'Belum berhasil masuk',
      failedDescription: 'Proses masuk belum selesai. Coba lagi dengan Google untuk melanjutkan.',
      retry: 'Coba lagi',
      accountTitle: 'Akun Kepotret',
      accountLoading: 'Memuat informasi akun…',
      accountError: 'Informasi akun belum dapat dimuat.',
      signOut: 'Keluar',
      inviteTitle: 'Undangan kolaborasi',
      inviteDescription: 'Masuk dengan Google untuk menerima undangan ini.',
      acceptInvite: 'Terima undangan',
      inviteSuccess: 'Undangan berhasil diterima.',
      inviteError: 'Undangan belum dapat diterima. Periksa kembali tautan atau coba lagi.',
      inviteInvalid: 'Tautan undangan tidak valid atau sudah tidak berlaku.',
      reauthTitle: 'Masuk kembali untuk melanjutkan',
      reauthDescription: 'Sesi kamu perlu diperbarui. Masuk kembali dengan akun Google untuk melanjutkan.',
      forbiddenTitle: 'Akses tidak tersedia',
      forbiddenDescription: 'Kamu tidak memiliki akses ke halaman ini.',
      home: 'Kembali ke Beranda',
    },
    system: {
      notFoundTitle: 'Halaman tidak ditemukan',
      notFoundDescription: 'Halaman yang kamu cari tidak tersedia atau alamatnya sudah berubah.',
      errorTitle: 'Halaman belum dapat dimuat',
      errorDescription: 'Terjadi kendala saat memuat halaman. Coba lagi, atau kembali ke Beranda.',
      maintenanceTitle: 'Layanan sedang dalam pemeliharaan',
      maintenanceDescription: 'Silakan coba kembali nanti.',
      compatibilityTitle: 'Buka Kepotret melalui browser',
      compatibilityDescription: 'Kepotret digunakan melalui browser di HP atau komputer. Untuk kontribusi foto, peserta menggunakan kamera browser; pemilihan foto dari galeri perangkat tidak tersedia.',
      retry: 'Coba lagi',
      home: 'Kembali ke Beranda',
    },
  },
  en: {
    nav: {
      how: 'How It Works',
      pricing: 'Pricing',
      faq: 'FAQ',
      signIn: 'Sign in',
      createAlbum: 'Create a Free Album',
      openMenu: 'Open navigation menu',
      closeMenu: 'Close navigation menu',
      switchToLight: 'Switch to light theme',
      switchToDark: 'Switch to dark theme',
      language: 'Language',
      indonesian: 'Indonesian',
      english: 'English',
    },
    hero: {
      eyebrow: 'PARTICIPATORY DOCUMENTATION FOR EVERY OCCASION',
      title: 'One moment. Many perspectives.',
      description: 'Do not miss the moments seen from another angle. The most special part may be waiting there. Share one QR code and let people at your event take photos directly from their phones.',
      proof: ['Photos gathered in one album', 'No app installation or participant account needed'],
      secondary: 'See How It Works',
      microcopy: 'Start for free',
      visualLabel: 'Moments from many perspectives',
      visualHint: 'Scan the QR. Take photos from your phone.',
    },
    how: {
      eyebrow: 'HOW IT WORKS',
      title: 'From QR to album in 3 steps.',
      description: 'You set up the album. Participants scan and take photos, then moments from different perspectives start coming together.',
      steps: [
        { title: 'Create an album', description: 'Set up an album for your event and choose your documentation needs.' },
        { title: 'Share the QR', description: 'Display the QR code at your event or share the link with participants.' },
        { title: 'Moments come together', description: 'They scan the QR, take photos from their phones, and the photos go into the same album.' },
      ],
      cta: 'See the Full Guide',
    },
    benefits: {
      eyebrow: 'WHY KEPOTRET',
      title: 'More perspectives. Less hassle.',
      description: 'Event documentation feels more alive when more people capture the moment. Kepotret brings it all together without making the process complicated.',
      items: [
        { title: 'Capture moments from more perspectives', description: 'Everyone sees something different. Bring those perspectives together in one album.' },
        { title: 'No need to ask for photos one by one', description: 'Photos that are successfully sent go straight into the event album, so you do not have to chase them individually.' },
        { title: 'Easy to join', description: 'Participants scan the QR and take photos from their phones, without installing an app or creating an account.' },
        { title: 'You stay in control', description: 'Choose when participants can take photos and when the gallery opens, and manage photos and album access for your event.' },
        { title: 'Flexible for busy events', description: 'Participant count is not limited by the package. Choose photo capacity for your needs without adjusting the package as more people join.' },
      ],
    },
    differentiation: {
      eyebrow: 'WHY KEPOTRET',
      title: 'Invite more people to capture the moment.',
      description: 'The number of participants does not determine your Kepotret package. Choose the photo capacity your event needs, then invite as many people as you like to capture the moment.',
      items: [
        { title: 'Download many photos at once', description: 'Need all the documentation? Hosts can prepare and download the album as a ZIP for convenience.' },
        { title: 'Control which photos are shown', description: 'Hosts can moderate, hide photos, and manage the photos shown to participants.' },
        { title: 'Invite your event organizer to help', description: 'Share album setup, moderation, or export work with your event organizer using the permissions you choose, so you can focus on the event.' },
        { title: 'Share easily through WhatsApp', description: 'Once photos can be viewed, share a photo link through WhatsApp or copy the link to send it to anyone.' },
      ],
    },
    useCases: {
      eyebrow: 'FOR EVERY OCCASION',
      title: 'Every event has moments seen from a different angle.',
      description: 'From personal events to large gatherings, Kepotret brings attendees’ perspectives together in one album.',
      items: [
        { title: 'Wedding & Celebration', description: 'Capture not only the main event, but also the expressions of family and friends and the atmosphere that one camera might miss.' },
        { title: 'Birthday & Personal Event', description: 'Gather spontaneous moments from the people closest to you without asking them to send photos one by one.' },
        { title: 'Community & Gathering', description: 'Let members and participants document the event from their own perspectives.' },
        { title: 'Sport & Competition', description: 'Capture the action, supporters, venue atmosphere, and moments after the match from more perspectives.' },
        { title: 'Corporate & Organization', description: 'Add participant perspectives to town halls, gatherings, offsites, and team activities.' },
        { title: 'Trip & Travel', description: 'One trip, many stories. Gather moments from your travel companions without photos scattered across phones.' },
      ],
    },
    guest: {
      eyebrow: 'PARTICIPANT EXPERIENCE',
      title: 'For participants, it is as simple as scan and shoot.',
      description: 'Participants do not need to install an app or create an account. They scan the QR, enter a name, allow camera access, and take photos directly from their phones.',
      steps: [
        { title: 'Scan the QR', description: 'Open the event QR or link directly from your phone.' },
        { title: 'Enter a name', description: 'Enter the name that will appear as the photo label.' },
        { title: 'Allow camera access', description: 'Allow camera access to start taking photos.' },
        { title: 'Take and use a photo', description: 'Take a photo, review it, then choose to use it or retake it.' },
      ],
      badges: ['No app installation', 'No participant account'],
      cta: 'See the Full Guide',
    },
    pricing: {
      eyebrow: 'PRICING',
      title: 'Choose capacity for your event.',
      description: 'Start free with 30 photos. Need more? Choose the photo capacity that fits your event—participant count is not limited by the package.',
      prompt: 'How many moments would you like to keep?',
      photoUnit: 'photos',
      free: 'Free',
      proof: ['Participant count is not limited by the package.', 'For one album.'],
      freeCta: 'Create a Free Album',
      paidCta: 'Choose {capacity} Photos',
    },
    trust: {
      eyebrow: 'CONTROL & SECURITY',
      title: 'Shared moments, still in your control.',
      description: 'Kepotret makes it easy to participate while keeping Hosts in control of their album, access, and the photos that are shown.',
      items: [
        { title: 'Choose who can view', description: 'Set album access for your needs, including an optional PIN.' },
        { title: 'Control which photos are shown', description: 'Hosts can moderate, hide photos, and manage the gallery before photos are shown to participants.' },
        { title: 'Clear access period', description: 'Albums have a scheduled access period, with reminders before access ends.' },
      ],
      cta: 'Learn About Security',
    },
    faq: {
      eyebrow: 'FAQ',
      title: 'Still have questions?',
      description: 'Here are a few things people often want to know before creating a Kepotret album.',
      items: [
        { question: 'Do participants need to install an app?', answer: 'No. Participants scan the QR or open the event link, then take photos directly from their phones in a browser.' },
        { question: 'Do participants need an account?', answer: 'No. Participants only enter a name to join and take photos. That name is used as the label on their photos.' },
        { question: 'How many participants can join?', answer: 'Participant count is not limited by the package. You choose the photo capacity for the album.' },
        { question: 'Can participants choose photos from their phone gallery?', answer: 'No. Kepotret album photos are taken directly with the camera while photo-taking is active.' },
        { question: 'When can participants view photos?', answer: 'The Host chooses when the gallery opens: D+1, D+3, D+5, or D+7 after the event ends. Photos that are not approved to appear remain hidden from participants.' },
        { question: 'How long can an album be accessed?', answer: 'Normal album access lasts until 30 days after the event ends. A limited 7-day recovery period then becomes available to the album owner before the main media is deleted.' },
        { question: 'Can photo capacity be increased when it is nearly full?', answer: 'Yes, while the upgrade period is still available. Purchases and upgrades close 120 minutes before the event ends.' },
        { question: 'Can an album be more private?', answer: 'Yes. Albums use link-based access, and Hosts can add an optional PIN, choose who can view the gallery, and manage which photos are shown.' },
      ],
      allQuestions: 'See all questions',
    },
    final: {
      title: 'See your next event from more perspectives.',
      description: 'Create a Kepotret album, share the QR, and let moments from different perspectives come together.',
      microcopy: 'Start for free',
    },
    footer: {
      brandLine: 'One moment. Many perspectives.',
      descriptor: 'Participatory documentation for every occasion.',
      product: 'Product',
      help: 'Help',
      legal: 'Legal',
      social: 'Follow us',
      helpCenter: 'Help Center',
      security: 'Security',
      contact: 'Contact us',
      privacy: 'Privacy Policy',
      terms: 'Terms of Service',
      unavailable: 'Unavailable',
      copyright: '© 2026 Kepotret. All rights reserved.',
      socialLabels: ['Instagram', 'TikTok', 'WhatsApp'],
    },
    publicPages: {
      howTitle: 'How Kepotret Works',
      howDescription: 'Set up an album, share the QR, and bring moments from many perspectives together in one album.',
      priceTitle: 'Pricing',
      faqTitle: 'Frequently asked questions',
      helpTitle: 'Help Center',
      helpDescription: 'For support and contact information, use Kepotret’s available official channels.',
      contactTitle: 'Contact us',
      unavailable: 'This information is not available yet.',
      privacyTitle: 'Privacy Policy',
      termsTitle: 'Terms of Service',
      legalUnavailable: 'The official document is not available yet.',
      securityTitle: 'Security & Privacy',
      securityDescription: 'Kepotret makes participation easy while keeping Hosts in control of their album, access, and the photos that are shown.',
    },
    auth: {
      signInTitle: 'Sign in to Kepotret',
      signInDescription: 'Use your Google account to sign in as a Host or continue with a collaborator invitation.',
      google: 'Continue with Google',
      processingTitle: 'Connecting to Google',
      processingDescription: 'We are preparing a secure sign-in. You will be redirected to Google.',
      failedTitle: 'Sign-in was not completed',
      failedDescription: 'Sign-in did not finish. Try again with Google to continue.',
      retry: 'Try again',
      accountTitle: 'Kepotret account',
      accountLoading: 'Loading account information…',
      accountError: 'Account information could not be loaded.',
      signOut: 'Sign out',
      inviteTitle: 'Collaborator invitation',
      inviteDescription: 'Sign in with Google to accept this invitation.',
      acceptInvite: 'Accept invitation',
      inviteSuccess: 'The invitation was accepted.',
      inviteError: 'The invitation could not be accepted. Check the link or try again.',
      inviteInvalid: 'This invitation link is invalid or no longer available.',
      reauthTitle: 'Sign in again to continue',
      reauthDescription: 'Your session needs refreshing. Sign in again with Google to continue.',
      forbiddenTitle: 'Access unavailable',
      forbiddenDescription: 'You do not have access to this page.',
      home: 'Back to home',
    },
    system: {
      notFoundTitle: 'Page not found',
      notFoundDescription: 'The page you are looking for is unavailable or its address has changed.',
      errorTitle: 'This page could not be loaded',
      errorDescription: 'Something went wrong while loading the page. Try again, or go back to the home page.',
      maintenanceTitle: 'Service is under maintenance',
      maintenanceDescription: 'Please try again later.',
      compatibilityTitle: 'Open Kepotret in a browser',
      compatibilityDescription: 'Kepotret runs in a browser on your phone or computer. Participants contribute photos using the browser camera; selecting photos from the device gallery is not available.',
      retry: 'Try again',
      home: 'Back to home',
    },
  },
} as const;

export type MarketingContent = (typeof content)['id'];

export function getContent(locale: Locale): MarketingContent {
  return content[locale] as unknown as MarketingContent;
}
