import { ArrowLeft, ArrowRight, Camera, Clock3, Images } from 'lucide-react';
import Link from 'next/link';
import { getLocale } from 'next-intl/server';

import { HelpFrame } from '@/features/help/help-frame';
import { helpContent, type HelpLocale } from '@/features/help/content';
import { hostRoutes } from '@/features/host/routes';

export default async function HostGuidePage() {
  const locale = await getLocale() as HelpLocale;
  const copy = helpContent[locale].host;
  const numberFor = (sectionIndex: number, stepIndex: number) => copy.sections.slice(0, sectionIndex).reduce((count, section) => count + section.steps.length, 0) + stepIndex + 1;
  return <HelpFrame locale={locale}><main className="mx-auto max-w-6xl px-4 pb-20 sm:px-6">
    <div className="py-8 sm:py-12"><Link href="/help" className="inline-flex min-h-11 items-center gap-2 text-sm font-semibold underline-offset-4 hover:underline"><ArrowLeft size={17} aria-hidden="true" />{copy.back}</Link><p className="mt-8 flex items-center gap-2 text-xs font-bold tracking-[.16em] text-[var(--color-muted-foreground)]"><span className="size-2.5 rounded-full bg-[var(--color-primary)] ring-1 ring-[var(--color-foreground)]" />{copy.eyebrow}</p><h1 className="mt-3 max-w-3xl font-[var(--font-display)] text-4xl font-bold tracking-tight sm:text-5xl">{copy.title}</h1><p className="mt-4 max-w-2xl text-base leading-7 text-[var(--color-muted-foreground)]">{copy.description}</p><div className="mt-6 flex flex-wrap items-center gap-4"><span className="rounded-full border border-[var(--color-border)] px-4 py-2 text-sm font-semibold">{copy.progress}</span><Link href={hostRoutes.createAlbum} className="inline-flex min-h-11 items-center gap-2 rounded-[var(--radius-md)] bg-[var(--color-primary)] px-4 text-sm font-semibold text-[var(--color-primary-foreground)]">{copy.start}<ArrowRight size={17} aria-hidden="true" /></Link></div></div>
    <div className="grid gap-8 lg:grid-cols-[14rem_minmax(0,1fr)] lg:gap-12"><aside><nav aria-label={copy.contents} className="lg:sticky lg:top-6"><details className="rounded-[var(--radius-lg)] border border-[var(--color-border)] bg-[var(--color-surface)] p-4 lg:hidden"><summary className="cursor-pointer font-semibold">{copy.contents}</summary><ol className="mt-3 space-y-1">{copy.sections.map((section, index) => <li key={section.id}><a href={`#${section.id}`} className="flex min-h-11 items-center gap-2 rounded px-2 text-sm hover:bg-[var(--color-muted)]"><span className="text-[var(--color-muted-foreground)]">{String(index + 1).padStart(2, '0')}</span>{section.title}</a></li>)}</ol></details><div className="hidden rounded-[var(--radius-lg)] border border-[var(--color-border)] bg-[var(--color-surface)] p-4 lg:block"><p className="px-2 text-xs font-bold uppercase tracking-[.14em] text-[var(--color-muted-foreground)]">{copy.contents}</p><ol className="mt-3 space-y-1">{copy.sections.map((section, index) => <li key={section.id}><a href={`#${section.id}`} className="flex min-h-11 items-center gap-2 rounded-[var(--radius-md)] px-2 text-sm hover:bg-[var(--color-muted)]"><span className="text-[var(--color-muted-foreground)]">{String(index + 1).padStart(2, '0')}</span>{section.title}</a></li>)}</ol></div></nav></aside>
      <div className="min-w-0 space-y-12">{copy.sections.map((section, index) => <section key={section.id} id={section.id} className="scroll-mt-8"><div className="border-b border-[var(--color-border)] pb-5"><p className="text-xs font-bold uppercase tracking-[.16em] text-[var(--color-muted-foreground)]">{String(index + 1).padStart(2, '0')} / {String(copy.sections.length).padStart(2, '0')}</p><h2 className="mt-2 font-[var(--font-display)] text-2xl font-bold sm:text-3xl">{section.title}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--color-muted-foreground)]">{section.lead}</p></div>{index === 0 && <div aria-hidden="true" className="mt-5 flex items-center gap-3 rounded-[var(--radius-md)] border border-[var(--color-border)] bg-[var(--color-muted)] px-4 py-3 text-xs font-semibold sm:text-sm"><Camera size={17} /><span className="size-2 rounded-full bg-[var(--color-primary)] ring-1 ring-[var(--color-foreground)]" /><Clock3 size={17} /><span className="h-px min-w-4 flex-1 bg-[var(--color-border)]" /><Images size={17} /></div>}<ol className="divide-y divide-[var(--color-border)]">{section.steps.map((step, stepIndex) => <li key={step.id} id={step.id} className="grid scroll-mt-8 gap-3 py-5 sm:grid-cols-[2.5rem_minmax(0,1fr)]"><span className="font-[var(--font-display)] text-xl font-bold text-[var(--color-muted-foreground)]">{String(numberFor(index, stepIndex)).padStart(2, '0')}</span><div><h3 className="font-[var(--font-display)] text-lg font-bold">{step.title}</h3><p className="mt-2 text-sm leading-6 text-[var(--color-muted-foreground)]">{step.body}</p>{step.note && <p className="mt-3 border-l-2 border-[var(--color-primary)] pl-3 text-sm leading-6">{step.note}</p>}</div></li>)}</ol></section>)}<section className="rounded-[var(--radius-lg)] bg-[#0a0a0a] p-6 text-white sm:p-8"><span className="inline-block size-3 rounded-full bg-[#d8ff3d]" aria-hidden="true" /><h2 className="mt-4 font-[var(--font-display)] text-2xl font-bold">{copy.finishTitle}</h2><p className="mt-3 max-w-lg text-sm leading-6 text-white/75">{copy.finishDescription}</p><Link href={hostRoutes.albums} className="mt-6 inline-flex min-h-11 items-center gap-2 rounded-[var(--radius-md)] bg-[#d8ff3d] px-4 text-sm font-semibold text-[#0a0a0a]">{copy.finishAction}<ArrowRight size={17} aria-hidden="true" /></Link></section></div>
    </div>
  </main></HelpFrame>;
}
